refactor: improve typing of vue-outside-click
vuestorefront/magento2 pull request #1008
Opened 2022-05-16 14:25 UTC by sethidden

Second batch of manual eslint fixes. Error/warning count is 140 -> 96

2022-05-16 14:26 UTC, sethidden commented on .eslintrc.js
> +        "jest/expect-expect": "off",
cypress uses similar test case syntax to jest so eslint gets confused and treats cypress like jest. this solution is not optimal but will do for now

2022-05-16 14:27 UTC, sethidden commented on packages/theme/package.json
> +    "body-parser": "1.19.2",
These were already used by body-parser.js - I'm just adding them explicitly, rather than using the transient versions provided by unrelated packages

2022-05-16 14:28 UTC, sethidden commented on packages/theme/tests/e2e/pages/checkout/Billing.ts
> +import { el } from '../utils/element';
Split one file with 4 classes into 4 files with 1 class each (eslint rule complaining)

2022-05-17 06:20 UTC, bartoszherba commented on packages/theme/tests/e2e/pages/checkout/Billing.ts
> +import { el } from '../utils/element';
Good :) This is how it should be done, one file - one class.

2022-05-17 06:21 UTC, bartoszherba requested changes
@sethidden Please, fix build issues.

2022-05-17 06:47 UTC, bartoszherba approved these changes

2022-05-17 06:47 UTC, merged