feat: add product to cart from wishlist
vuestorefront/magento2 pull request #1026
Opened 2022-05-19 12:46 UTC by AlexanderDevitsky

## Description

## Related Issue

https://vsf.atlassian.net/browse/M2-502

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-05-19 12:47 UTC, AlexanderDevitsky commented
@bartoszherba should I create unit-tests in the scope of this task?

2022-05-20 06:58 UTC, bartoszherba commented
@AlexanderDevitsky I must put this on hold for a while, if you look at this draft https://github.com/vuestorefront/magento2/pull/1014 you will realize why. There will be multiple problems like we no longer can have business logic on the product page. I also do not like the fact that we base on the locale path as the solution is not generic, eg. if someone will add a wishlist somewhere else, or create a different path for a subaccount, or [name it] it will not work. I need to think of how it can be solved. For now we must hold this PR ;(

2022-05-20 07:24 UTC, sethidden commented on packages/theme/modules/catalog/pages/product.vue
> +          )} to your shopping cart.`) as string,
Please pass product name as parameter to the label. We can't possibly make thousands of translation labels for each product name

https://kazupon.github.io/vue-i18n/guide/formatting.html#named-formatting

```suggestion
          message: i18n.t(`You added productname to your shopping cart.`, { productname: getProductName(product.value)} ) as string,
```

This won't render the product name after this change obviously, so you'll need to add that to the translations in en.js, de.js like `'You added productname to your shopping cart': 'You added {productname} to your shopping cart'`.

Don't forget to do that in MyWishlist aswell.

@bartoszherba is it ok to add new translation labels like that?

2022-05-20 07:26 UTC, bartoszherba commented on packages/theme/modules/catalog/pages/product.vue
> +          )} to your shopping cart.`) as string,
No, the product's translation comes from Magento. We mustn't translate it on the front. Good catch, thanks.

2022-05-20 07:30 UTC, sethidden requested changes

2022-05-20 07:30 UTC, sethidden commented on packages/theme/modules/catalog/pages/product.vue
> +      if (from.value?.path === localePath('/customer/my-wishlist')) {
1. Wondering if it wouldn't be easier to just redirect to the product page with some query parameter `/p/product?from-wishlist` - that way if someone refreshes the page the "fromWishlist" information won't be lost

2. Shouldn't this be a computed?

3. If the query paramater doesn't work, it'll be easier to maybe use the route *name*, not the route path

```suggestion
      if (from.value?.name === localeRoute({ name: 'customer-my-wishlist' })) {
```

(see modules/customer/index.ts for route name)

2022-05-20 07:30 UTC, sethidden commented on packages/theme/modules/customer/pages/MyAccount/MyWishlist.vue
> +          } else if (cartError.value.addItem.message) {
```suggestion
          } else {
```

would that work? I don't think errors can have missing messages

2022-05-20 09:55 UTC, AlexanderDevitsky commented
@bartoszherba In this case, we need to extend Magento GraphQL schema by adding a 'remove_from_wishlist' field. Then implement the logic of removing a product from the wishlist on the Magento side. As I understand it, for the default theme, we cannot use additional implementations for Magento, but must use only the default implementation. Therefore, this option is not possible.
Currently, the referrer url is only used to remove configurable product when navigating to it from the wishlist.
If a product needs to be removed from the wishlist anyway, not just when added from the wishlist, then we just need to check if it's on the wishlist and using referrer url is redundant.
When https://github.com/vuestorefront/magento2/pull/1014 is finished, let me know and we will find a better solution for this.

2022-05-20 09:56 UTC, AlexanderDevitsky commented on packages/theme/modules/customer/pages/MyAccount/MyWishlist.vue
> +          } else if (cartError.value.addItem.message) {
@sethidden I think the message should be there anyway, so this can be removed

2022-05-20 10:37 UTC, bartoszherba commented
@AlexanderDevitsky 
PR is merged, I am sorry for that inconvenience.

With regards to the solution:

I think that we can make it work as @sethidden suggested. I did a small POC and reworked the query build in `product.vue` to something like, for a query parameter `wishlist=true` => example `http://localhost:3000/default/p/WJ01/stellar-solar-jacket.html?wishlist=true&OTM%3D=Y29uZmlndXJhYmxlLzkzLzYw&MTQ0=Y29uZmlndXJhYmxlLzE0NC8xNjk%3D`
```
const getBaseSearchQuery = () => ({
      filter: {
        sku: {
          eq: id,
        },
      },
      configurations: Object.entries(route.value.query)
        .filter((config) => config[0] !== 'wishlist')
        .map(
          (config) => config[1],
        ) as string[],
    });
```

Now, we can trigger wishlist mode on any PDP page with this flag from any place simply by passing the query param and we are not tight to the account page. If you look on the Magento, there is something very similar, as the add-to-wishlist has its own controller.

That would be the first step.

The second step is to have generic and reusable addToWishlist logic, separated from PDP (unlike you did in your PR which is justified by how it looked at that time).
Important thing is to keep business logic out of components, especially out of the page. This is not completely done at this moment because I did not want to keep such a huge change any longer, but this is the goal, so by introducing a new feature we can do it right from the very beginning.

@sethidden @AlexanderDevitsky What do you think?

2022-05-20 10:42 UTC, AlexanderDevitsky commented
@bartoszherba Good solution

2022-05-20 12:01 UTC, bartoszherba requested changes
Please, review all comments.

2022-05-20 16:44 UTC, AlexanderDevitsky commented
@bartoszherba @sethidden I have added new changes. Please review if this is the right solution for us

2022-05-23 06:52 UTC, bartoszherba requested changes
@AlexanderDevitsky 
Thank you for changes, just last 2 small comments and we are done here ;)

2022-05-23 06:52 UTC, bartoszherba commented on packages/theme/modules/customer/pages/MyAccount/MyWishlist.vue
>          case 'BundleProduct':
could you please add GroupedProduct? I know that it is not your change but I just noticed that. Also, you can replace it with `packages/theme/modules/catalog/product/enums/ProductTypeEnum.ts`

2022-05-23 06:52 UTC, bartoszherba commented on packages/theme/modules/wishlist/composables/useWishlist/index.ts
> +import productGetters from '~/modules/catalog/product/getters/productGetters';
Could you please remove that and simply `product.name` in the code? We will remove most of the getters and we avoid using getters in new code unless it is necessary, eg. when getter execute some additional logic.

2022-05-23 09:42 UTC, AlexanderDevitsky commented on packages/theme/modules/customer/pages/MyAccount/MyWishlist.vue
>          case 'BundleProduct':
done

2022-05-23 09:42 UTC, AlexanderDevitsky commented on packages/theme/modules/wishlist/composables/useWishlist/index.ts
> +import productGetters from '~/modules/catalog/product/getters/productGetters';
done

2022-05-23 10:20 UTC, bartoszherba approved these changes

2022-05-24 06:28 UTC, bartoszherba approved these changes

2022-05-24 06:38 UTC, Frodigo approved these changes

2022-05-25 13:00 UTC, sethidden approved these changes

2022-05-26 05:36 UTC, merged