test: Added tests for CategorySidebar component
vuestorefront/magento2 pull request #1028
Opened 2022-05-19 13:47 UTC by Diegoalbag

## Description

Added unit tests for packages/theme/modules/catalog/category/components/sidebar/CategorySidebar.vue
## Related Issue

https://vsf.atlassian.net/jira/software/c/projects/M2/boards/51?modal=detail&selectedIssue=M2-441
## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):
<img width="561" alt="Screen Shot 2022-05-19 at 9 43 07 AM" src="https://user-images.githubusercontent.com/72459310/169307830-da84d115-5e62-45f0-becf-723c2155894a.png">

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2022-05-20 06:34 UTC, bartoszherba requested changes
@Diegoalbag 
A few additional things to do
1. Please, rework all scripts from js to ts, I know it might be misleading that most tests are in js but this is in most cases a legacy code and was not updated yet. All new tests/mocks/utils/scripts-in-general are in TS.

2. Please, add additional tests: 
- if the user click on a category without children he will be redirected to that category
- if the user click on a category with children deeper categories will be revealed
- if the user click on the back arrow (not the go back button) menu will be hidden

2022-05-20 06:34 UTC, bartoszherba commented on packages/theme/modules/catalog/category/components/sidebar/MobileCategorySidebar/__tests__/MobileCategorySidebar.spec.js
> +    useCategoryStore.mockReturnValue(categoryMock);
Can we extract common part for all tests and execute it in beforeEach?

2022-05-20 06:34 UTC, bartoszherba commented on packages/theme/modules/catalog/category/components/sidebar/MobileCategorySidebar/__tests__/MobileCategorySidebar.spec.js
> +jest.mock('~/modules/catalog/category/stores/category', () => ({
Please, separate mocks setup with empty lines for a readability

2022-05-20 14:04 UTC, Diegoalbag commented on packages/theme/modules/catalog/category/components/sidebar/MobileCategorySidebar/__tests__/MobileCategorySidebar.spec.js
> +    useCategoryStore.mockReturnValue(categoryMock);
OK

2022-05-20 14:04 UTC, Diegoalbag commented on packages/theme/modules/catalog/category/components/sidebar/MobileCategorySidebar/__tests__/MobileCategorySidebar.spec.js
> +jest.mock('~/modules/catalog/category/stores/category', () => ({
OK

2022-05-23 06:43 UTC, bartoszherba requested changes

2022-05-23 06:43 UTC, bartoszherba commented on packages/theme/modules/catalog/category/components/sidebar/MobileCategorySidebar/__tests__/MobileCategorySidebar.spec.js
> +jest.mock('~/modules/catalog/category/stores/category', () => ({
Ok, but you did not do that? Each jest.mock must be separated with an empty line.

2022-05-23 06:43 UTC, bartoszherba commented on packages/theme/modules/catalog/category/components/sidebar/MobileCategorySidebar/__tests__/MobileCategorySidebar.spec.js
> +    useCategoryStore.mockReturnValue(categoryMock);
Ok === you did or you will extract it?

2022-05-30 07:05 UTC, Frodigo commented
@bartoszherba if you have a chance, please re-review this one, thanks!

2022-05-31 10:56 UTC, bartoszherba approved these changes

2022-05-31 11:09 UTC, merged