refactor: fix eslint warnings in .vue files
vuestorefront/magento2 pull request #1036
Opened 2022-05-20 12:47 UTC by sethidden

Continued fixes of eslint, but this time in .vue files.

Turned out that a huge amount of .vue errors were in a file that contained some SVG tags.

AFter this PR, there are 30 errors left - most are about missing lang="ts"

2022-05-22 10:19 UTC, sethidden commented
Added lang="ts" to some more components. There are 17 errors left. Most are lang="ts", but adding lang="ts" obviously makes that one error turn into seven.

2022-05-23 06:38 UTC, bartoszherba requested changes

2022-05-23 06:38 UTC, bartoszherba commented on packages/theme/pages/Page.vue
> +    // eslint-disable-next-line consistent-return
Is this still required? maybe add return value instead of suppressing linter.

2022-05-23 06:38 UTC, bartoszherba commented on packages/theme/pages/Page.vue
> +    const page : CmsPage = this.page;
```suggestion
    const { page }: CmsPage = this;
```

2022-05-23 06:38 UTC, bartoszherba commented on packages/theme/pages/Page.vue
> +import { CmsPage, useContent } from '~/composables';
Please, import CmsPage from GraphQL module.

2022-05-23 06:38 UTC, bartoszherba commented on packages/theme/pages/Page.vue
> +    const page : CmsPage = this.page;
Anyway, there is something wrong with this type if you destruct the value, is the page really CmsPage?

2022-05-23 07:07 UTC, sethidden commented on packages/theme/pages/Page.vue
> +    // eslint-disable-next-line consistent-return
https://nuxtjs.org/docs/directory-structure/middleware/#named-middleware

Given the example above I don't think there's anything to return. If I add just `return` the linter will complain about "useless return"

2022-05-23 07:24 UTC, sethidden commented on packages/theme/pages/Page.vue
> +    const page : CmsPage = this.page;
Avoided destructuring with type assertion by using a solution from nuxt/typescript (link in commit message)

2022-05-23 08:45 UTC, Frodigo approved these changes

2022-05-23 10:18 UTC, bartoszherba approved these changes

2022-05-23 10:43 UTC, merged