docs: add composables docs
vuestorefront/magento2 pull request #1062
Opened 2022-05-25 13:49 UTC by filipsobol

2022-05-26 05:54 UTC, Frodigo approved these changes
Thanks for that @filipsobol, it's awesome! 

Please resolve conflicts.

2022-05-26 17:08 UTC, filipsobol commented
@Frodigo I resolved the conflict. I also asked @bartoszherba to review certain parts of these docs that we discussed

2022-05-27 06:29 UTC, bartoszherba commented on docs/composition/composables.md
> +2. Next, we call the asynchronous `load` method within the `useFetch` lifecycle hook to load user data.
```suggestion
2. Next, we call the asynchronous `load` method within the `useFetch` hook to load user data.
```

2022-05-27 06:32 UTC, bartoszherba commented on docs/composition/composables.md
> +### `useFetch` and other lifecycle hooks for data-fetching
Hey, useFetch is just a hook, not a lifecycle hook, lifecycle hooks -> https://vuejs.org/api/composition-api-lifecycle.html
useFetch though is executed with the usage of lifecycle hooks internally, a few of them - so it spans over multiple phases.

2022-05-27 06:35 UTC, bartoszherba commented on docs/composition/composables.md
> +Now that you understand what composables are, you should see the [List of composables](./list-of-composables.html) and their options.
In the list of composables, external checkout composable is not finished yet.

2022-05-27 06:38 UTC, bartoszherba commented on docs/composition/list-of-composables.md
> +## `useExternalCheckout`
Can we mark this one as unfinished?

2022-05-27 06:41 UTC, bartoszherba requested changes
All is good but useFetch description must be changes to avoid naming this hook as a lifecycle hook, please check https://composition-api.nuxtjs.org/lifecycle/usefetch/

2022-05-27 06:46 UTC, bartoszherba commented on docs/composition/list-of-composables.md
> +Allows searching for products using facets. It accepts multiple filters, allowing to narrow down the results to a specific category, search term, etc.
I am not sure about this, this is basically `products` query but the response is extended by pagination, totals, and sorting options, so it is not about searching with the usage of something like `facet` but to have a response enriched with additional data, where some are not even fetched from the API.

2022-05-27 06:48 UTC, bartoszherba commented on docs/composition/list-of-composables.md
> +Allows showing notifications to the user.
More like helps manage notifications? I mean, showing notifications is just a part of its functions.

2022-05-27 13:47 UTC, bartoszherba approved these changes

2022-05-27 14:22 UTC, merged