test: added tests for selectedfilters component
vuestorefront/magento2 pull request #1067
Opened 2022-05-26 11:02 UTC by AlexanderDevitsky

## Description

## Related Issue

https://vsf.atlassian.net/browse/M2-436

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-05-27 05:42 UTC, Frodigo requested changes

2022-05-27 05:42 UTC, Frodigo commented on packages/theme/modules/catalog/category/components/filters/FiltersSidebar/__tests__/SelectedFilters.spec.ts
> +    expect(container.querySelector('.selected-filter')).toBeNull();
Please use here `findByTestId('selected-filter')`

2022-05-27 05:42 UTC, Frodigo commented on packages/theme/modules/catalog/category/components/filters/FiltersSidebar/__tests__/SelectedFilters.spec.ts
> +    selectedFilers.forEach((filter) => {
Remove this for each, please.

2022-05-27 11:02 UTC, AlexanderDevitsky commented on packages/theme/modules/catalog/category/components/filters/FiltersSidebar/__tests__/SelectedFilters.spec.ts
> +    expect(container.querySelector('.selected-filter')).toBeNull();
findBy query returns a promise if the element is found and throws an error if the element doesn't exist, so async/await construction should be used with it. I decided to use queryByTestId. Perhaps this is better?
<img width="633" alt="Screenshot 2022-05-27 at 13 54 07" src="https://user-images.githubusercontent.com/14941520/170687419-191bea94-7b41-45ac-b2c5-f464b142b97d.png">

2022-05-27 11:02 UTC, AlexanderDevitsky commented on packages/theme/modules/catalog/category/components/filters/FiltersSidebar/__tests__/SelectedFilters.spec.ts
> +    selectedFilers.forEach((filter) => {
removed

2022-05-27 11:17 UTC, Frodigo commented on packages/theme/modules/catalog/category/components/filters/FiltersSidebar/__tests__/SelectedFilters.spec.ts
> +    expect(container.querySelector('.selected-filter')).toBeNull();
yes, sorry I meant queryBy, so my mistake. Yes, go ahead with queryBy!

2022-05-27 11:22 UTC, AlexanderDevitsky commented on packages/theme/modules/catalog/category/components/filters/FiltersSidebar/__tests__/SelectedFilters.spec.ts
> +    expect(container.querySelector('.selected-filter')).toBeNull();
done

2022-05-27 11:49 UTC, Frodigo submitted a review, later dismissed

2022-05-27 13:57 UTC, bartoszherba commented on packages/theme/modules/catalog/category/components/filters/FiltersSidebar/__tests__/SelectedFilters.spec.ts
> +});
Can we also test if `yes/no` label is rendered properly?

2022-05-30 11:48 UTC, AlexanderDevitsky commented on packages/theme/modules/catalog/category/components/filters/FiltersSidebar/__tests__/SelectedFilters.spec.ts
> +});
@bartoszherba added

2022-05-30 13:16 UTC, Frodigo approved these changes

2022-05-30 13:16 UTC, merged