refactor: m2-528. refactored useUrlResolver to use the route query
vuestorefront/magento2 pull request #1078
Opened 2022-05-30 12:53 UTC by Frodigo

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-05-30 16:00 UTC, sethidden commented on packages/api-client/src/types/GraphQL.ts
> +export type RouteQuery<ROUTE_TYPE> = {
This file is autogenerated. Don't modify it. Or does it come from Magento's GraphQL endpoint? If this is hand-written by you please move it to a separate .ts file

2022-05-30 16:07 UTC, sethidden commented on packages/theme/modules/catalog/pages/category.vue
> +    const routeData = ref<CategoryTree>(null);
```suggestion
    const routeData = ref<CategoryTree | null>(null);
```

we don't have strict null checks in typescript but pedantism

2022-05-30 16:08 UTC, sethidden commented on packages/theme/composables/useUrlResolver/index.ts
> +    let results = null;
```suggestion
    let results : EntityUrl | null = null;
```
Don't remove the type assertion. Right now the type of results is "any"

2022-05-30 16:09 UTC, sethidden commented on packages/theme/composables/useUrlResolver/index.ts
> +    let results = null;
If EntityUrl doesn't work now please use something else that fits

2022-05-30 16:13 UTC, sethidden commented on packages/api-client/src/api/urlResolver/index.ts
> + * @deprecated - use route query instead
https://github.com/vuestorefront/magento2/pull/1078/files#r884967163
Regarding the linked comment, I think it'd be easier to actually point to what the user is supposed to use. If I read this comment i wouldn't know what to use instead.

whereas
```suggestion
 * @deprecated - use getRoute instead
```
is more exact

2022-05-30 16:14 UTC, sethidden requested changes
Left some comments

2022-05-30 18:24 UTC, Frodigo commented on packages/api-client/src/types/GraphQL.ts
> +export type RouteQuery<ROUTE_TYPE> = {
ok

2022-05-30 18:29 UTC, Frodigo commented on packages/theme/modules/catalog/pages/category.vue
> +    const routeData = ref<CategoryTree>(null);
fixed.

2022-05-30 18:36 UTC, Frodigo commented on packages/theme/composables/useUrlResolver/index.ts
> +    let results = null;
fixed, but I had a problem with wrong generic type and I needed to add @ts-ignore in one line below.

2022-05-30 18:37 UTC, Frodigo commented on packages/api-client/src/api/route/index.ts
> +export default async function route<ROUTE_TYPE extends RoutableInterface>(
I See, but better will be resolveRoute.

2022-05-30 18:38 UTC, Frodigo commented on packages/api-client/src/api/urlResolver/index.ts
> + * @deprecated - use route query instead
ok, thanks!

2022-05-31 05:39 UTC, bartoszherba commented on packages/api-client/src/api/route/index.ts
> +export type RouteQuery<ROUTE_TYPE> = {
Generic type `ROUTE_TYPE` is redundant and gives nothing. In your code, you do not use any field of method that belongs to a possible generic that actually extends RoutableInteface. All you need is the RoutableInterface because all calls are done on this interface's API. There is no conditional logic for any other type anywhere. You should get rid of the generic type and replace it with RoutableInterface only.

2022-05-31 05:44 UTC, bartoszherba commented on packages/api-client/src/api/route/index.ts
> +export default async function resolveRoute<ROUTE_TYPE extends RoutableInterface>(
To follow the convention we already have in the API, the method should be named the same as the endpoint route, in this case, `route`. Please, check other index files and methods names. For product the name is the product, for placeOrder the name is placeOrder, and so on.

2022-05-31 05:47 UTC, bartoszherba requested changes
I think that the Router type must be removed.

2022-05-31 05:48 UTC, sethidden requested changes
Can we please fix the ts-ignore? The error should be fixable, for example with Bartek's suggestions. If not, we can hop on a call

2022-05-31 05:49 UTC, sethidden commented on packages/api-client/src/api/route/index.ts
> +export default async function resolveRoute<ROUTE_TYPE extends RoutableInterface>(
https://github.com/vuestorefront/magento2/pull/1078#discussion_r884967163

2022-05-31 05:53 UTC, sethidden commented on packages/theme/composables/useUrlResolver/index.ts
> +    let results = null;
Wouldn't count ts-ignore as a fix unless there's some third party TS mistake :P Hopefully Bart's comment about removing the generic should help

2022-05-31 07:14 UTC, Frodigo commented on packages/api-client/src/api/route/index.ts
> +export type RouteQuery<ROUTE_TYPE> = {
I don't agree with you. Route query returns a specific type like CategoryTree or SimpleProduct. In case when you need to use a field of that type in the code like that: 

```
const { search: resolveUrl } = useUrlResolver();

routeData.value = await resolveUrl(); 
getContentData(routeData.value?.uid),
```
TS reports a problem because uid does not exist on RoutableInterface type. Then, we need a Generic type here that extends from RoutableInterface.

2022-05-31 07:17 UTC, Frodigo commented on packages/api-client/src/api/route/index.ts
> +export default async function resolveRoute<ROUTE_TYPE extends RoutableInterface>(
I see your point and I'm going to restore my change and name the function as `route`

2022-05-31 07:24 UTC, bartoszherba commented on packages/theme/modules/catalog/pages/category.vue
> +import type { CategoryTree } from '@vue-storefront/magento-api';
```suggestion
import type { CategoryTree } from '~/modules/GraphQL/types';
```

2022-05-31 07:25 UTC, bartoszherba commented on packages/api-client/src/api/route/index.ts
> +export type RouteQuery<ROUTE_TYPE> = {
You are right.

2022-05-31 07:46 UTC, Frodigo commented on packages/theme/composables/useUrlResolver/index.ts
> +    let results = null;
After chatting with Bartek, the generic type need to stay here. I tried to fix ts-ignore but without success. Could you check out my branch and check that by yourself?

2022-06-01 12:32 UTC, sethidden submitted a review, later dismissed

2022-06-03 07:05 UTC, bartoszherba approved these changes

2022-06-03 07:09 UTC, merged