docs: add Getting started section
vuestorefront/magento2 pull request #1121
Opened 2022-06-13 09:12 UTC by filipsobol

This PR adds `Getting started` section to the docs

2022-06-14 11:19 UTC, Frodigo requested changes

2022-06-14 11:19 UTC, Frodigo commented on docs/getting-started/project-structure.md
> +If you followed our [Installation](/installation-setup/installation.html) guide, you should have a Vue Storefront project with some e-commerce platform already integrated. This project has a bunch of
I wonder, if this is a part of Magento docs, it should be described like : "you should have a Vue Storefront project with Magento platform already integrated" instead of "you should have a Vue Storefront project with some e-commerce platform already integrated."

2022-06-14 11:19 UTC, Frodigo commented on docs/getting-started/project-structure.md
> +// TODO: Describe what `composables` folder contains
Do you plan to add this information and resolve this todo and the next ones in this file?

2022-06-14 11:19 UTC, Frodigo commented on docs/getting-started/internationalization.md
> +**Please note that only one currency can be set for each locale.**
It's not correct. In Magento, you can have multiple currencies for one locale and it depends on Magento configuration.

2022-06-14 11:19 UTC, Frodigo commented on docs/getting-started/internationalization.md
> +## Configuring the Auto Cookie Change
We removed the i18n VSF module from the core so this part is not necessary.

2022-06-15 09:41 UTC, filipsobol commented on docs/getting-started/internationalization.md
> +## Configuring the Auto Cookie Change
Which part exactly? `Configuring the Auto Cookie Change` and `Configuring cookie attributes` sections or only the first one?

2022-06-15 09:41 UTC, filipsobol commented on docs/getting-started/internationalization.md
> +**Please note that only one currency can be set for each locale.**
Removed

2022-06-23 07:21 UTC, Frodigo commented on docs/getting-started/internationalization.md
> +## Configuring the Auto Cookie Change
Both, because we disabled the i18n cookie plugin from @vuestorefront/nuxt module. Take a look at nuxt.config for reference.

2022-06-23 09:17 UTC, filipsobol commented on docs/getting-started/internationalization.md
> +## Configuring the Auto Cookie Change
Done ✅

2022-06-30 09:08 UTC, Frodigo commented on docs/getting-started/project-structure.md
> +// TODO: Describe what `composables` folder contains
@filipsobol I added description for folders

2022-06-30 09:15 UTC, filipsobol commented on docs/getting-started/project-structure.md
> +// TODO: Describe what `composables` folder contains
Looks good 👍

2022-06-30 13:08 UTC, matthewmaribojoc approved these changes

2022-07-01 09:53 UTC, merged