fix: fixed order details 500 error
vuestorefront/magento2 pull request #1134
Opened 2022-06-15 10:52 UTC by Frodigo

Redirect to the order history page when single order does not exist in a store.

2022-06-15 12:09 UTC, sethidden requested changes

2022-06-15 12:09 UTC, sethidden commented on packages/theme/modules/customer/pages/MyAccount/OrderHistory/SingleOrder/SingleOrder.vue
> +        return null;
```suggestion
        router.push(context.localeRoute( { name: 'customer-order-history' } ));

        return null;
```

2022-06-17 06:25 UTC, Frodigo commented on packages/theme/modules/customer/pages/MyAccount/OrderHistory/SingleOrder/SingleOrder.vue
> +        return null;
Fixed, thanks!

2022-06-17 07:21 UTC, sethidden approved these changes

2022-06-17 07:30 UTC, merged