perf: category page CLS improvement
vuestorefront/magento2 pull request #1179
Opened 2022-06-29 07:47 UTC by bartoszherba

## Description
category page CLS improvement

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-06-29 07:49 UTC, bartoszherba commented on packages/theme/modules/catalog/category/components/views/CategoryProductGrid.vue
> -  <transition-group
This is to prevent opacity, transition issue reports

2022-06-29 07:49 UTC, bartoszherba commented on packages/theme/modules/catalog/category/components/views/CategoryProductGrid.vue
> +    height: 257px;
Because of the lack of control over SFUI components, I had to take some space to prevent content jump.

2022-06-29 07:55 UTC, Frodigo requested changes
I need more time to analyze and review this. I will back to you with comments later.

2022-06-30 09:57 UTC, Frodigo approved these changes

2022-06-30 09:57 UTC, merged