feat: secure cookie attribute is not set
vuestorefront/magento2 pull request #1232
Opened 2022-07-08 09:20 UTC by bartoszherba

## Description
I have added configurable cookies options so it will be possible to customize cookies set mods.

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-07-08 09:22 UTC, bartoszherba commented on packages/theme/middleware.config.js
> +          secure: false,
If I set this === true then we will have to change it for local development if we do not have ssl, which is true in most cases. If I leave it as it is, cookies will remain non-secure on our demo envs.

2022-07-11 11:12 UTC, Frodigo commented on packages/theme/middleware.config.js
> +          secure: false,
As we talked about in person, it would be great to enable it in our environments using nuxt.config.addtional.js file.

2022-07-12 06:49 UTC, bartoszherba commented on packages/theme/middleware.config.js
> +          secure: false,
1. I set the flag to true as we should setup the app to be as safe as possible OOTB
2. I added the instruction of how to setup SSL certificate (it is straightforward and will take no more than 1 min)

2022-07-12 07:19 UTC, Frodigo commented on docs/installation-setup/configure-integration.md
> +### Install `mkcert`
Can you add information how to install it on Windows? In addition, please add link to tool that you use: https://github.com/FiloSottile/mkcert

2022-07-12 07:21 UTC, Frodigo requested changes
Looks good, one request about adding docs for Windows users

2022-07-12 08:20 UTC, Frodigo approved these changes

2022-07-12 08:41 UTC, merged