docs: updated installation guide
vuestorefront/magento2 pull request #1239
Opened 2022-07-11 11:08 UTC by Frodigo

### Before
Installation command that was described `vsf init` has been depracated so our docks was not up tom date

### After
We updated the readme files and installation guide to use `npx @vue-storefront/cli generate store` so the documentation is up to date.

2022-07-11 11:52 UTC, filipsobol commented on README.md
> +npx @vue-storefront/cli generate store && cd <project_name> && yarn && yarn dev
To not have to maintain this in the future, I suggest adding a link to Installation guide: https://docs.vuestorefront.io/magento/installation-setup/installation.html

2022-07-11 11:53 UTC, filipsobol commented on packages/api-client/README.md
> +npx @vue-storefront/cli generate store && cd <project_name> && yarn && yarn dev
To not have to maintain this in the future, I suggest adding a link to the Installation guide: https://docs.vuestorefront.io/magento/installation-setup/installation.html

2022-07-11 11:53 UTC, filipsobol commented on packages/composables/README.md
> +npx @vue-storefront/cli generate store && cd <project_name> && yarn && yarn dev
To not have to maintain this in the future, I suggest adding a link to the Installation guide: https://docs.vuestorefront.io/magento/installation-setup/installation.html

2022-07-11 11:54 UTC, filipsobol commented on README.md
> +npx @vue-storefront/cli generate store && cd <project_name> && yarn && yarn dev
To not have to maintain this in the future and have one source of truth, I suggest adding a link to the Installation guide: https://docs.vuestorefront.io/magento/installation-setup/installation.html

2022-07-11 11:55 UTC, filipsobol requested changes

2022-07-11 11:55 UTC, filipsobol commented on packages/api-client/README.md
> +npx @vue-storefront/cli generate store && cd <project_name> && yarn && yarn dev
To not have to maintain this in the future and have one source of truth, I suggest adding a link to the Installation guide: https://docs.vuestorefront.io/magento/installation-setup/installation.html

2022-07-11 11:55 UTC, filipsobol commented on packages/composables/README.md
> +npx @vue-storefront/cli generate store && cd <project_name> && yarn && yarn dev
To not have to maintain this in the future and have one source of truth, I suggest adding a link to the Installation guide: https://docs.vuestorefront.io/magento/installation-setup/installation.html

2022-07-11 12:17 UTC, bartoszherba approved these changes

2022-07-12 09:04 UTC, Frodigo commented on packages/api-client/README.md
> +npx @vue-storefront/cli generate store && cd <project_name> && yarn && yarn dev
Added.

2022-07-13 11:16 UTC, filipsobol approved these changes

2022-07-13 11:17 UTC, merged