fix: getAvailableShippingMethods query variables
vuestorefront/magento2 pull request #1318
Opened 2022-08-01 11:50 UTC by sequensucks

Replace a cart_id getAvailableShippingMethods query variable with a cartId

fix #1264

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-08-01 12:48 UTC, Frodigo requested changes

2022-08-01 12:48 UTC, Frodigo commented on packages/api-client/src/api/getAvailableShippingMethods/GuestAvailableShippingMethods.ts
>      cart(cart_id:$cart_id) {
Once you changed `$cart_id` to `$cartId`, you need to change it here: `cart_id:$cartId`

2022-08-01 14:42 UTC, filrak commented
Thanks for your contribution @sequensucks!

2022-08-02 07:30 UTC, Frodigo approved these changes

2022-08-02 07:30 UTC, merged