feat: implement magento url rewrites
vuestorefront/magento2 pull request #1321
Opened 2022-08-02 08:39 UTC by sequensucks

## Description
Use a magento route graphql query and implement seo-friendly urls for product, category and cms
pages

BREAKING CHANGE: Change a urls pattern for product, category, cms pages

## Related Issue
re #181

## Motivation and Context

## How Has This Been Tested?
Check all urls for product, category, cms pages 

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2022-08-02 12:24 UTC, Frodigo requested changes
Good job at all, thanks! 

I added some initial comments. Please take a look.

2022-08-02 16:32 UTC, sequensucks commented on packages/api-client/src/api/route/route.ts
> +        sku
Sorry, i use this query on my project and forgot to remove unused fields. Fixed

2022-08-02 16:33 UTC, sequensucks commented on packages/theme/composables/index.ts
> -export * from './useUrlResolver';
Restored it.

2022-08-02 16:34 UTC, sequensucks commented on packages/theme/middleware/url-resolver.ts
> +  // @ts-ignore
Removed a ts-ignore. There is no error here.

2022-08-02 16:35 UTC, sequensucks commented on packages/theme/middleware/url-resolver.ts
> +const middleware : Middleware = async (context) => {
added a ~/middleware/__tests__/url-resolver.spec.js

2022-08-02 16:38 UTC, sequensucks commented on packages/theme/modules/catalog/getters/pageGetters.ts
> +export interface PageGetters {
Removed this method. We don't need it.
I replaced __typename with type and renamed pages components. After these changes we don't need an extra method.

2022-08-02 16:38 UTC, sequensucks commented on packages/theme/modules/catalog/product/getters/productGetters.ts
> +export const getProductPath = (product: ProductInterface) => {
Moved to useProduct

2022-08-03 11:53 UTC, Frodigo commented on packages/theme/middleware/url-resolver.ts
> +const middleware : Middleware = async (context) => {
Thanks!

2022-08-03 11:53 UTC, Frodigo commented on packages/theme/modules/catalog/product/getters/productGetters.ts
> +export const getProductPath = (product: ProductInterface) => {
great, thanks!

2022-08-03 12:00 UTC, sethidden commented on packages/api-client/src/api/route/route.ts
> +      ... on SimpleProduct {
All of these product variants inherit for ProductInterface. The top-level type that creates "uid" is `ProductInterface`, not the child `SimpleProduct`, `GroupedProduct` itp.

So theoretically the duplicated `sku`s could be remove and just 
```
query aaa {
  route(url: "something") {
    ... on ProductInterface {
      uid
    }
  }
}
```
would work

2022-08-03 12:05 UTC, sequensucks commented on packages/api-client/src/api/route/route.ts
> +      ... on SimpleProduct {
oh, thank you! I tested it and it works perfect! I will update a query.

2022-08-03 13:10 UTC, sequensucks commented on packages/api-client/src/api/route/route.ts
> +      ... on SimpleProduct {
updated the query

2022-08-03 13:36 UTC, sequensucks commented
@Frodigo ofc! 
- moved `page.vue`, `cms.vue` pages to packages/theme/pages
- and moved `~/modules/catalog/store/page.ts` to `~/stores/page.ts`

2022-08-05 11:38 UTC, Frodigo approved these changes

2022-08-05 11:38 UTC, merged