feat: implement a standalone cart page
vuestorefront/magento2 pull request #1328
Opened 2022-08-09 11:37 UTC by sequensucks

Create a cart module. Implement a standalone cart page. Fix useCart linters and cartGetters linters.
Move an useCart composable, a cartGetters and cart store to the cart module.

re #340

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-08-16 06:43 UTC, bartoszherba commented
Hello, @sequensucks,
Thank you for your PR.
There are general issues that I want to be fixed before we move deeper into the solutions.

1. We mustn't change the namespace of the cart logic (checkout -> cart module). In Magento, the cart is a part of the checkout module and we want to reflect that, also - the cart is a part of the checkout process so it does make sense to keep it as it was. In addition, such a change will affect everyone and adds not enough value to justify it.
2. If I understand your change correctly, there will be no sidebar cart, and this is a huge change. We can't make such a shift without thinking of the existing projects. If there should be a standalone cart page then it must be a configurable option such it works as previously unless someone changes the option flag. Then we will avoid breaking change but provide a feature. 
3. Please, use the PR template, put pieces of information into relevant fields, and mark checklist boxes.

2022-08-16 06:44 UTC, bartoszherba requested changes
@sequensucks Please, read my general comments.

2022-08-16 06:48 UTC, sequensucks commented
@bartoszherba thank you for your review.
I will fix all general issues

2022-08-16 09:54 UTC, bartoszherba commented
@sequensucks I think that a more proper approach to the cart, instead of a configurable option, would be to do the same as in the M2 Luma theme, there is a cart sidebar, but on the bottom of the sidebar, there is an additional button to go to the cart page.

2022-08-16 11:49 UTC, sequensucks commented
@bartoszherba i restored a cart sidebar and added a go to cart button.

2022-08-18 07:44 UTC, bartoszherba requested changes
Further work in a few points:

1. remove unnecessary changes according to comments, like in getters, imports, empty lines removal and so on..
2. Extract duplicated cart business logic into a separate composable and reuse it in both Cart and CartSidebar

2022-08-18 07:44 UTC, bartoszherba commented on packages/theme/components/AppHeader.vue
> -      toggleCartSidebar,
Please, switch that back, this is an unnecessary change. It looks like a harmless thing but whenever someone will try to update his project he will notice the difference here in files. It is always a rule of thumb to introduce the smallest possible amount of changes.

2022-08-18 07:44 UTC, bartoszherba commented on packages/theme/components/BottomNavigation.vue
> +      toggleCartSidebar,
The same here as in the previous comment.

2022-08-18 07:44 UTC, bartoszherba commented on packages/theme/components/CartSidebar.vue
> -                  :image="cartGetters.getItemImage(product)"
In general, this is not a bad change or good, it depends on the view. But to follow the rule of the smallest amount of changes, please revert all getters update.
Also, in the future, we can introduce one PR with such an update if this is really an improvement, but if we do that in a dedicated task, it will be easier to prepare a migration guide or understand changes. Now, in the task with a standalone cart, we also include getters refactorization, and that is too much. Please, revert all changes for cart/product/... getters.

2022-08-18 07:44 UTC, bartoszherba commented on packages/theme/components/CartSidebar.vue
> +    };
Please, add a new line after this function block.

2022-08-18 07:44 UTC, bartoszherba commented on packages/theme/components/CartSidebar.vue
> -
Please, revert that empty line removal (here and in the further code to separate function blocks).

2022-08-18 07:44 UTC, bartoszherba commented on packages/theme/components/CartSidebar.vue
> +}
Add a new line after this block, and remove empty lines removal in the further CSS code. Each block must be separated with a new line.

2022-08-18 07:44 UTC, bartoszherba commented on packages/theme/components/__tests__/CartSidebar.spec.ts
> -import { render, waitFor, within } from '@testing-library/vue';
Why did you remove this file? If test is failing, please update the test.

2022-08-18 07:44 UTC, bartoszherba commented on packages/theme/lang/en.js
> +  "Go to cart": "Go to cart",
Please, add the translation for the German language too.

2022-08-18 07:44 UTC, bartoszherba commented on packages/theme/modules/catalog/product/components/product-types/bundle/BundleProductSelector.vue
> +import { useCart } from '~/modules/checkout/composables/useCart';
```suggestion
import useCart from '~/modules/checkout/composables/useCart';
```

2022-08-18 07:44 UTC, bartoszherba commented on packages/theme/modules/catalog/product/components/product-types/grouped/GroupedProductSelector.vue
> +import { useCart } from '~/modules/checkout/composables/useCart';
```suggestion
import useCart from '~/modules/checkout/composables/useCart';
```

2022-08-18 07:44 UTC, bartoszherba commented on packages/theme/modules/checkout/components/CartPreview.vue
> +import { useCart } from '~/modules/checkout/composables/useCart';
```suggestion
import useCart from '~/modules/checkout/composables/useCart';
```

2022-08-18 07:44 UTC, bartoszherba commented on packages/theme/modules/checkout/components/VsfShippingProvider.vue
> +import { useCart } from '~/modules/checkout/composables/useCart';
```suggestion
import cartGetters from '~/modules/checkout/getters/cartGetters';
import useCart from '~/modules/checkout/composables/useCart';
```

2022-08-18 07:44 UTC, bartoszherba commented on packages/theme/modules/checkout/composables/useBilling/index.ts
> +import { useCart } from '~/modules/checkout/composables/useCart';
```suggestion
import useCart from '~/modules/checkout/composables/useCart';
```

2022-08-18 07:44 UTC, bartoszherba commented on packages/theme/modules/checkout/composables/useMakeOrder/index.ts
> +import type { UseMakeOrderErrors, UseMakeOrderInterface } from './useMakeOrder';
Please, revert.

2022-08-18 07:44 UTC, bartoszherba commented on packages/theme/modules/checkout/composables/usePaymentProvider/index.ts
> +import { CustomQuery } from '~/types/core';
Revert.

2022-08-18 07:44 UTC, bartoszherba commented on packages/theme/modules/checkout/composables/useShipping/index.ts
> +import { useCart } from '~/modules/checkout/composables/useCart';
Please, revert here and everywhere else.

2022-08-18 07:44 UTC, bartoszherba commented on packages/theme/modules/checkout/pages/Cart.vue
> +    const goToCheckout = async () => {
A lot of code here is duplicated (CartSidebar). Please, add composable with business logic and reuse it in the Cart and CartSidebar components. Also, I think that we should move CartSidebar from a theme/components to modules/checkout/components/CartSidebar.

Examples of duplicated methods are: `goToCheckout` or `sendToRemove` but there are more.

2022-08-18 07:44 UTC, bartoszherba commented on packages/theme/modules/checkout/pages/Cart.vue
> +    };
Please, add the new line after block.

2022-08-18 07:44 UTC, bartoszherba commented on packages/theme/modules/checkout/pages/Cart.vue
> +    const isInStock = (product: CartItemInterface) => getStockStatus(product) === ProductStockStatus.InStock;
Please, add the new line after block.

2022-08-18 07:44 UTC, bartoszherba commented on packages/theme/modules/checkout/pages/Cart.vue
> +}
Please, add the new line after the block. (and everywhere in the further code)

2022-08-23 08:44 UTC, bartoszherba requested changes

2022-08-23 08:44 UTC, bartoszherba commented on packages/theme/modules/checkout/helpers/useCartBaseSetup.ts
> +import {
- Please, rename the file `useCartBaseSetup` -> `useCartView` and move it into the module's composables.
- add docblocks in the same way as for other composables
- write unit tests for the `useCartView` compsable

2022-08-23 08:44 UTC, bartoszherba commented on packages/theme/modules/checkout/helpers/useCartBaseSetup.ts
> +  const visible = ref(false);
```suggestion
  const isRemoveModalVisible = ref(false);
```

2022-08-23 08:44 UTC, bartoszherba commented on packages/theme/modules/checkout/helpers/useCartBaseSetup.ts
> +  const sendToRemove = ({ product }: { product: CartItemInterface }) => {
```suggestion
  const showRemoveItemModal = ({ product }: { product: CartItemInterface }) => {
```

2022-08-23 08:44 UTC, bartoszherba commented on packages/theme/modules/checkout/helpers/useCartBaseSetup.ts
> +    visible.value = true;
```suggestion
    isRemoveModalVisible.value = true;
```

2022-08-23 08:44 UTC, bartoszherba commented on packages/theme/modules/checkout/helpers/useCartBaseSetup.ts
> +  const tempProduct = ref();
```suggestion
  const itemToRemove = ref<CartItemInterface>();
```

2022-08-23 08:44 UTC, bartoszherba commented on packages/theme/modules/checkout/helpers/useCartBaseSetup.ts
> +    tempProduct.value = product;
```suggestion
    itemToRemove.value = product;
```

2022-08-23 08:44 UTC, bartoszherba commented on packages/theme/modules/checkout/helpers/useCartBaseSetup.ts
> +    visible.value = false;
```suggestion
    isRemoveModalVisible.value = false;
```

2022-08-23 08:44 UTC, bartoszherba commented on packages/theme/modules/checkout/helpers/useCartBaseSetup.ts
> +  const actionRemoveItem = async (product: CartItemInterface) => {
```suggestion
  const removeItemAndSendNotification = async (product: CartItemInterface) => {
```

2022-08-23 08:44 UTC, bartoszherba commented on packages/theme/modules/checkout/helpers/useCartBaseSetup.ts
> +    visible,
```suggestion
    isRemoveModalVisible,
```

2022-08-23 08:49 UTC, sequensucks commented
@bartoszherba I will make changes after vacation. From 1.09

2022-08-24 13:03 UTC, sequensucks commented
@bartoszherba added a changes from the last review, but without unit tests. will add tests after a vacation.

2022-08-30 08:16 UTC, sequensucks commented
Hello @bartoszherba,
No, I fixed the CartSidebar unit tests after adding an useCartView composable.
And i want to add unit tests for the useCartView composable. But it will be after 1.09.

2022-09-05 07:00 UTC, sequensucks commented
Hello @bartoszherba,
Sorry for no answer a long time. I checked a PR and i think it is a final version. You can review it. Thank you!

2022-09-05 07:16 UTC, bartoszherba commented
@sequensucks And what about tests we have been talking about recently? Could you add tests for the useCartView composable?

2022-09-19 06:50 UTC, bartoszherba approved these changes

2022-09-19 06:51 UTC, merged