fix: fix a message about submitted review
vuestorefront/magento2 pull request #1331
Opened 2022-08-09 19:18 UTC by sequensucks

fix #1226

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-08-16 06:31 UTC, bartoszherba requested changes

2022-08-16 06:31 UTC, bartoszherba commented on packages/theme/modules/catalog/product/components/ProductAddReviewForm.vue
> +      <p>{{ $t('You submitted your review for moderation.') }}</p>
This message is not appropriate because moderation is an optional setting in the Magento. We must add more generic, I think that the previous one was ok. Unfortunately there is no way to read the actual setting from Magento.

2022-08-16 06:31 UTC, bartoszherba commented on packages/theme/modules/catalog/product/components/tabs/ProductTabs.vue
> +    const isReviewsLoading = ref(true);
How is this change address issue #1226? If this is a different problem, please create a separate PR to fix it.

2022-08-16 06:37 UTC, sequensucks commented on packages/theme/modules/catalog/product/components/tabs/ProductTabs.vue
> +    const isReviewsLoading = ref(true);
when we use a loading from useReview a list of reviews rerender when we are adding a new review.
And an actual result is a list of reviews, but we want to see a submitted message.

2022-08-16 06:43 UTC, sequensucks commented on packages/theme/modules/catalog/product/components/ProductAddReviewForm.vue
> +      <p>{{ $t('You submitted your review for moderation.') }}</p>
The message from an issue
https://github.com/vuestorefront/magento2/issues/1226

We could create a new param(boolean) is_product_review_ moderation in the .env.

2022-08-18 07:48 UTC, bartoszherba commented on packages/theme/lang/en.js
> +  "You submitted your review for moderation.": "You submitted your review for moderation.",
Please, add the german translation.

2022-08-18 07:49 UTC, bartoszherba commented on packages/theme/modules/catalog/product/components/ProductAddReviewForm.vue
> +      <p>{{ $t('You submitted your review for moderation.') }}</p>
Ok, let it be as it is. It does not hurt to say that the review will be moderated event if the moderation is disabled.

2022-08-18 07:51 UTC, bartoszherba commented on packages/theme/modules/catalog/product/components/tabs/ProductTabs.vue
> +    const isReviewsLoading = ref(true);
Ok.

2022-08-18 07:53 UTC, bartoszherba requested changes
Please, add german translation and we can move on.

2022-08-18 08:19 UTC, sequensucks commented
@bartoszherba added from a google translate. I don't know german=)

2022-08-18 11:39 UTC, bartoszherba approved these changes

2022-08-18 11:39 UTC, bartoszherba commented
@sequensucks Please, fix conflicts.

2022-08-18 12:07 UTC, sequensucks commented
@bartoszherba merged a current develop branch

2022-08-19 07:51 UTC, bartoszherba commented
@sequensucks Please, resolve conflicts.

2022-08-19 07:53 UTC, sequensucks commented
@bartoszherba merged a current develop branch

2022-08-19 08:07 UTC, bartoszherba commented
@sequensucks There are still conflicts.

2022-08-19 08:10 UTC, sequensucks commented
i synchronized a fork and merged into my branch.

2022-08-23 08:44 UTC, bartoszherba commented
@sequensucks How's going on solving conflicts?

2022-08-23 08:52 UTC, sequensucks commented
@bartoszherba  i don't know where is a problem=(
i haven't conflicts.
I clicked a sync a fork (develop branch).
and merged a develop to my branch. Got up to date and nothing to merged.
Github is saying 
<img width="1052" alt="image" src="https://user-images.githubusercontent.com/89065178/186115757-fff7beaa-945d-4678-9207-0edea0307f56.png">

2022-08-23 14:45 UTC, merged