feat: implement custom headers
vuestorefront/magento2 pull request #1365
Opened 2022-09-15 12:17 UTC by sequensucks

## Description

Add custom headers for all queries and mutations
## Related Issue
re #1364

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2022-09-21 07:09 UTC, bartoszherba requested changes

2022-09-21 07:09 UTC, bartoszherba commented on packages/theme/composables/useConfig/index.ts
> +      const { data } = await app.$vsf.$magento.api.storeConfig(params?.customQuery ?? null, params?.customHeaders ?? null);
Could you do this everywhere?

```const def = {test: true};
const fun = (val = {}) => {
 console.log({...def, ...val});
}
fun(def?.doesNotExistsProp);
```
Yields 
```
{
  test: true
}
```
So the ?? null is redundant in all cases.

```suggestion
      const { data } = await app.$vsf.$magento.api.storeConfig(params?.customQuery, params?.customHeaders);
```

2022-09-21 07:15 UTC, bartoszherba commented
@sequensucks Please, add guide for the custom headers in the documentation `docs/guide/custom-headers.md`

2022-09-21 07:22 UTC, sequensucks commented on packages/api-client/src/api/getHeaders.ts
>      ...(getCurrency() && { 'Content-Currency': getCurrency() }),
2 cases. First, we give users to change all headers. Second, we don't give users to change required headers.

2022-09-21 07:28 UTC, bartoszherba commented on packages/api-client/src/api/getHeaders.ts
>      ...(getCurrency() && { 'Content-Currency': getCurrency() }),
Exactly the opposite.
```
const obj = {a: true, b: true};
const custom = { a: false };
console.log('case1', {...custom, ...obj});
console.log('case2', {...obj, ...custom});

"case1", {
  a: true,
  b: true
}
"case2", {
  a: false,
  b: true
}
```

2022-09-21 07:30 UTC, sequensucks commented on packages/api-client/src/api/getHeaders.ts
>      ...(getCurrency() && { 'Content-Currency': getCurrency() }),
Yes, if ...customHeaders will be first, we don't give users to change required headers. If i change it, users will be able to change all headers.

2022-09-21 07:34 UTC, bartoszherba commented on packages/api-client/src/api/getHeaders.ts
>      ...(getCurrency() && { 'Content-Currency': getCurrency() }),
This is why we introduce custom headers, to allow users to change headers. Do you see any risks? I do not. Each default header can be easily manipulated in another way.

2022-09-21 13:32 UTC, sequensucks commented on packages/api-client/src/api/getHeaders.ts
>      ...(getCurrency() && { 'Content-Currency': getCurrency() }),
fixed it

2022-09-21 13:32 UTC, sequensucks commented on packages/api-client/src/api/getHeaders.ts
> +export default function getHeaders(context: Context, customHeaders: Record<string, string> = {}) {
fixed it.

2022-09-27 12:39 UTC, bartoszherba approved these changes

2022-09-27 12:40 UTC, merged