chore(docs): fix docs deployment
vuestorefront/magento2 pull request #1396
Opened 2022-11-24 19:14 UTC by bloodf

## Description
Fixed the documentation deployment due to outdated packages and missing configurations.
Fixed components developed with the emit function called a Vue object directive.

The current implementation was only working due to the version being installed sometimes getting the correct version of packages, causing some deploys to hang out.

With this fix, another current process needs more discovery, as there are a lot of `API-references` files, and the VuePress bundling process is taking a lot of time to be executed.

## Related Issue
N/A

## Motivation and Context
The current documentation is not being deployed and hanging out in GitHub. An investigation was done, and it was checked that some packages were miss-installed due to bad versions, and components were not fully following the composition API structure.

## How Has This Been Tested?

The building of the docs, and validation of the same was done locally.

The code was checked if it was building, and executing against a Magento 2 interface, so no breaking changes occurs in this process.

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2022-11-25 07:33 UTC, bartoszherba requested changes
Please, remove all changes that are not connected with a docs deployment fix. Also, do not merge to the main branch unless it is a critical hotfix.

2022-11-25 07:44 UTC, bartoszherba requested changes
Please, remove ALL changes that are not related to the docs build. Revert ALL packages upgrade that are not related to docs, especially for most important libraries like the apollo-client. Create a PR to the develop branch. Thanks.

2022-11-25 07:44 UTC, bartoszherba commented on docs/package.json
> +    "caniuse-lite": "latest",
What are these dependencies? Why do we need them? Also, the "latest" or any "fluid" version is error-prone, please define the version.

2022-11-25 07:44 UTC, bartoszherba commented on docs/package.json
> +    "typescript": "<=4.7.4",
Is typescript 1.0.0 ok? Why is this necessary to fix docs build?

2022-11-25 07:44 UTC, bartoszherba commented on package.json
> +    "prepare": "husky install",
How does it affect docs?

2022-11-25 07:44 UTC, bartoszherba commented on package.json
> +    "yargs": "^17.6.2"
Which exactly package affects docs build? Please, revert other changes.

2022-11-25 07:44 UTC, bartoszherba commented on packages/api-client/package.json
>      "webpack": "4.46.0"
Revert all critical updates that are not required for docs build. Especially apollo clients. This is not something you can just update and push to the main without the QA phase....

2022-11-25 07:44 UTC, bartoszherba commented on packages/theme/components/CurrencySelector/CurrenciesModal.vue
> +<script lang='ts'>
Please, remove all changes from this file. It is not something related to the docs build.

2022-11-25 07:44 UTC, bartoszherba commented on packages/theme/components/StoreSwitcher/StoresModal.vue
> -<script lang="ts">
Same here, only docs build changes are acceptable.

2022-12-01 17:05 UTC, bloodf commented on package.json
> +    "prepare": "husky install",
It was affecting the process of the lifecycle of the repository.

2022-12-01 17:08 UTC, bloodf commented on package.json
> +    "yargs": "^17.6.2"
The packages were updated because there was a lot of error is displayed due to mix and matches of dependencies sub-dependencies. 

Those updates were made after a long checking session, so we don't have conflicting dependencies.

2022-12-01 17:08 UTC, bloodf commented on packages/api-client/package.json
>      "webpack": "4.46.0"
The packages were updated because there was a lot of error is displayed due to mix and matches of dependencies sub-dependencies. 

Those updates were made after a long checking session, so we don't have conflicting dependencies.

2022-12-01 20:05 UTC, bloodf commented
@bartoszherba I've updated the description, also with why those changes were made, including screenshots of the errors.

2022-12-05 05:25 UTC, closed without merging