Add translations to label on UserAccount
vuestorefront/magento2 pull request #1405
Opened 2022-12-08 11:40 UTC by bensinca

Add translations for user account newsletter, login and create account inputs.

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-12-11 16:54 UTC, bartoszherba requested changes
Please, resolve the marked issue, update the title so the checks pass, check the proper checkboxes in the issue description and change the target branch to develop.

2022-12-11 16:54 UTC, bartoszherba commented on packages/theme/modules/checkout/pages/Checkout/UserAccount.vue
> +        :label="$t('Login on the store')"
Please, add this sentence to the dictionary.

2022-12-13 10:54 UTC, bartoszherba commented on packages/theme/lang/en.js
> +  "Login on the store": "Login on the store",
Please, add translations also to the de.js file, you can use the translator for such simple sentences. The goal here is to avoid excessive warnings in the console.

2022-12-13 18:15 UTC, bensinca commented on packages/theme/lang/en.js
> +  "Login on the store": "Login on the store",
I am sorry, I don't feel comfortable doing that - regardless, I can close this PR and you can just do it if you wish.

2022-12-13 18:21 UTC, bensinca commented on packages/theme/lang/en.js
> +  "Login on the store": "Login on the store",
Initially, I didn't feel comfortable doing this - but if you're ok with Google Translate then I don't mind.

2022-12-20 12:01 UTC, merged