feat(in-4412): logger in magento api
vuestorefront/magento2 pull request #1559
Opened 2024-12-09 12:42 UTC by lsliwaradioluz

[IN-4412](https://alokai.atlassian.net/browse/IN-4412)

[IN-4412]: https://alokai.atlassian.net/browse/IN-4412?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-12-10 10:16 UTC, bartoszherba requested changes

2024-12-10 10:16 UTC, bartoszherba commented on packages/api-client/src/api/cmsPage/index.ts
> +      logger.debug(error);
```suggestion
      logger.error(error);
```

2024-12-10 10:16 UTC, bartoszherba commented on packages/api-client/src/api/productDetails/index.ts
> +      logger.debug(error);
```suggestion
      logger.error(error);
```

2024-12-10 10:16 UTC, bartoszherba commented on packages/api-client/src/api/products/index.ts
> +      logger.debug(error);
```suggestion
      logger.error(error);
```

2024-12-10 10:16 UTC, bartoszherba commented on packages/api-client/src/api/requestPasswordResetEmail/index.ts
> +  logger.debug("[VSF: Magento] requestPasswordResetEmail", input);
Logger already have contextual data so `[VSF: Magento]` is redundant. Also, I think that we should either remove this debug log or improve the message verbosity and clarity - end user should be able to get a profit from such message, I doubt he can now.

2024-12-10 10:16 UTC, bartoszherba commented on packages/api-client/src/api/resetPassword/index.ts
> +  logger.debug("[VSF: Magento] requestPasswordResetEmail", input);
Same here.

2024-12-10 10:16 UTC, bartoszherba commented on packages/api-client/src/helpers/magentoLink/graphQl.ts
> +            logger.error(`[GraphQL error]: Message: ${message}, Path: ${path}`);
We should use `metadata` instead of [GraphQL error].
Also, the first argument is the message.
Path should be also a metadata.

2024-12-10 10:16 UTC, bartoszherba commented on packages/api-client/src/helpers/magentoLink/graphQl.ts
> +          logger.error(`[GraphQL error]: Message: ${message}, Location: ${parsedLocations.join(", ")}, Path: ${path}`);
Same fixes here.

2024-12-10 10:16 UTC, bartoszherba commented on packages/api-client/src/helpers/magentoLink/graphQl.ts
> +      logger.error(`[Network error]: ${networkError}`);
Network error can be a metadata kind. the network error can be logged directly
```suggestion
      logger.error(networkError, { type: 'Network Error'});
```
The type is just a proposition. We do not have convention here.

2024-12-10 10:16 UTC, bartoszherba commented on packages/api-client/src/helpers/magentoLink/index.ts
> +  logger.debug("createMagentoConnection");
I think that this debug is useless.

2024-12-10 10:16 UTC, bartoszherba commented on packages/api-client/src/helpers/magentoLink/linkHandlers.ts
> +      logger.debug(`Apollo retry-link, the operation (${operation.operationName}) sent with wrong token, creating a new one... (attempt: ${count})`);
it should be an error, also maybe operation and count can be metadata? (optional)

2024-12-10 10:16 UTC, bartoszherba commented on packages/api-client/src/helpers/magentoLink/linkHandlers.ts
> +      logger.debug(`Apollo authLinkFactory, finished, token: ${token}`);
I do not understand the value of these logs.

2024-12-10 11:22 UTC, lsliwaradioluz commented on packages/api-client/src/api/requestPasswordResetEmail/index.ts
> +  logger.debug("[VSF: Magento] requestPasswordResetEmail", input);
The best I can do is [this](https://github.com/vuestorefront/magento2/pull/1559/commits/010f50cbc7334c663022d3d71d1c1c9d2ef8cc7d)

2024-12-10 11:24 UTC, lsliwaradioluz commented on packages/api-client/src/api/resetPassword/index.ts
> +  logger.debug("[VSF: Magento] requestPasswordResetEmail", input);
The best I can do is [this](https://github.com/vuestorefront/magento2/pull/1559/commits/71a2bde277ef1b953285a98b6b0e42dfc857e3de)

2024-12-10 11:26 UTC, lsliwaradioluz commented on packages/api-client/src/helpers/magentoLink/graphQl.ts
> +            logger.error(`[GraphQL error]: Message: ${message}, Path: ${path}`);
like [this](https://github.com/vuestorefront/magento2/pull/1559/commits/ee1b521db286f8a888433d5d0fa83a546d7bc1e8)?

2024-12-10 11:26 UTC, lsliwaradioluz commented on packages/api-client/src/helpers/magentoLink/graphQl.ts
> +          logger.error(`[GraphQL error]: Message: ${message}, Location: ${parsedLocations.join(", ")}, Path: ${path}`);
like [this](https://github.com/vuestorefront/magento2/pull/1559/commits/ee1b521db286f8a888433d5d0fa83a546d7bc1e8)?

2024-12-10 11:32 UTC, lsliwaradioluz commented on packages/api-client/src/helpers/magentoLink/index.ts
> +  logger.debug("createMagentoConnection");
Tbh I have the same opinion, [removed](https://github.com/vuestorefront/magento2/pull/1559/commits/db118f5782dc193c3b35f8a140cc63df7addf968)

2024-12-10 11:37 UTC, lsliwaradioluz commented on packages/api-client/src/helpers/magentoLink/linkHandlers.ts
> +      logger.debug(`Apollo retry-link, the operation (${operation.operationName}) sent with wrong token, creating a new one... (attempt: ${count})`);
Like [this](https://github.com/vuestorefront/magento2/pull/1559/commits/c3ea649e5a6f3dcc1f4ca6b96063ffcaecb2d67d)?

2024-12-10 11:41 UTC, lsliwaradioluz commented on packages/api-client/src/helpers/magentoLink/linkHandlers.ts
> +      logger.debug(`Apollo authLinkFactory, finished, token: ${token}`);
I guess while debugging they're just useful to see where we are at in the code execution flow, even though they do not provide very meaningful information on variables or parameters. Nevertheless, I think they won't hurt - I have only refactored their messages and metadata [here](https://github.com/vuestorefront/magento2/pull/1559/commits/a14ad7627d8421521b29a5cd9fb11ab7f1334707).

2024-12-11 17:06 UTC, bartoszherba approved these changes

2024-12-12 09:17 UTC, merged