fix(theme): 256 customer account - address creation navigation issue
vuestorefront/magento2 pull request #258
Opened 2021-12-07 13:21 UTC by bartoszherba

Fix issue #256

## Description
Rework customer account navigation to address #256 issue

## Related Issue
Bug #256

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-12-07 15:37 UTC, bloodf approved these changes

2021-12-07 15:38 UTC, bloodf requested changes

2021-12-07 15:38 UTC, bloodf commented on packages/theme/routes.js
> +    path: '/my-account/:pageName?/:addressId?',
Instead of a parameter, can we use a URL Query?

2021-12-07 15:38 UTC, bloodf commented on packages/theme/pages/MyAccount/AddressesDetails.vue
> +      await router.push({ path: `/my-account/addresses-details/${addressId}` });
What if we use a URL query to fetch the details, so we don't mess with the routering?

2021-12-07 15:42 UTC, bartoszherba commented on packages/theme/pages/MyAccount/AddressesDetails.vue
> +      await router.push({ path: `/my-account/addresses-details/${addressId}` });
The problem with query is that it is not really SEO friendly because of the quotation mark. As we have our custom routing configuration, adding optional parameter is not a big deal, parameter is eventually accessible in router and can be used to conditionally display things or keep address info between pages.

2021-12-07 19:56 UTC, Frodigo commented on packages/theme/pages/MyAccount/AddressesDetails.vue
> +      await router.push({ path: `/my-account/addresses-details/${addressId}` });
@bloodf, can you elaborate on what you mean by messing with the routing? 

The second question is, what is an advantage of using URL query instead of routing in this case?

2021-12-08 15:07 UTC, bloodf commented on packages/theme/pages/MyAccount/AddressesDetails.vue
> +      await router.push({ path: `/my-account/addresses-details/${addressId}` });
This page is not even an SEO page, because it's hidden under the MyAccount interface, so it needs to be logged in to be accessed.

The problem with adding new parameters to the routering is that you will add the same parameter that will be valid in all the `my-account` namespace, so if we are on the `my-account/my-orders` the `addressId` will be a valid parameter. 

When using the Query Parameters, you will add the same value without interfering with others' namespace, and in this case, it won't be a problem at all for SEO as this is not found by any SEO robot, as they need to be logged in to use this route.

2021-12-08 20:21 UTC, bartoszherba commented on packages/theme/pages/MyAccount/AddressesDetails.vue
> +      await router.push({ path: `/my-account/addresses-details/${addressId}` });
Thanks fo reply, I do not know wy I write SEO, what I had in mind was not user friendly url, but in both cases your arguments applies I think. I just updated the PR.

2021-12-08 20:37 UTC, bloodf approved these changes

2021-12-08 20:38 UTC, merged