feat(theme): add reusable AddToWishlist component
vuestorefront/magento2 pull request #288
Opened 2021-12-12 17:15 UTC by bartoszherba

Introduction of a new reusable AddToWishlist component

## Description
Currently add to wishlist functionality is available only in places where product cart is used. With new component that functionality can be reused anywhere.

## Related Issue
#278

## How Has This Been Tested?

1. Log in, as the action on the PDP is available only for logged in customers
2. Below add to cart there is Add To Wishlist action
3. Adding to wishlist should be reflected in global wishlist 

## Screenshots (if appropriate):
<img width="557" alt="Screenshot 2021-12-12 at 18 12 34" src="https://user-images.githubusercontent.com/16045377/145722344-1eee0db2-208f-4b8c-a96c-fb275e043898.png">
<img width="556" alt="Screenshot 2021-12-12 at 18 14 20" src="https://user-images.githubusercontent.com/16045377/145722349-0fd5810b-1cd4-4ddf-ba3a-ed9ef6a71bf8.png">

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-12-13 00:24 UTC, bloodf approved these changes

2021-12-13 00:28 UTC, bloodf requested changes

2021-12-13 00:28 UTC, bloodf commented on packages/theme/pages/Product.vue
> +                />
We need to add the verification if the user is authenticated. Because the Wishlist will only show for authenticated users.

2021-12-13 07:00 UTC, Frodigo commented
Hi @bartoszherba I would like to ask it is possible to use this component on the Category page as well?

2021-12-13 07:02 UTC, Frodigo requested changes

2021-12-13 07:02 UTC, Frodigo commented on packages/theme/components/AddToWishlist.vue
> +    const actionText = computed(() => (props.isInWishlist ? 'Remove from wishlist' : 'Add to wishlist'));
Nevermind, I see it is translatable :)

2021-12-13 12:14 UTC, bartoszherba commented on packages/theme/pages/Product.vue
> +                />
:is-show="isAuthenticated"
This part is responsible for that.

2021-12-13 12:16 UTC, bartoszherba commented on packages/theme/components/AddToWishlist.vue
> +    isShow: {
I would rather not, visibility in web context means that something is rendered but can be either visible or not. In my case there will be no html at all so it makes more sense.

2021-12-13 16:47 UTC, Frodigo commented on packages/theme/components/AddToWishlist.vue
> +    isShow: {
I see your point, thanks.

2021-12-14 03:15 UTC, Frodigo approved these changes
Hi, @bartoszherba thanks for your contribution. This is approved!

2021-12-14 03:59 UTC, bloodf approved these changes

2021-12-14 04:02 UTC, merged