Bugfix/266
vuestorefront/magento2 pull request #314
Opened 2021-12-16 03:14 UTC by bloodf

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-12-16 08:13 UTC, Frodigo requested changes

2021-12-16 08:13 UTC, Frodigo commented on package.json
> +    "yarn": "1.x"
How about yarn 2, or 3? It will work?

2021-12-16 08:13 UTC, Frodigo commented on packages/api-client/package.json
> +    "cross-fetch": "^3.1.4",
Can you explain the reason why we need to change from node-fetch to cross-fetch? Just for better understanding, thanks!

2021-12-16 08:13 UTC, Frodigo commented on packages/api-client/package.json
> -    "@vue-storefront/core": "~2.5.2",
@vue-storefront/core is no longer necessary here?

2021-12-16 08:13 UTC, Frodigo commented on packages/api-client/package.json
> -    "@vue-storefront/core": "~2.5.2",
Ok I see it's added as a peer dependency.

2021-12-16 08:13 UTC, Frodigo commented on packages/api-client/src/helpers/magentoLink/graphQl.ts
> +} from '@apollo/client/core';
Can be @apollo/client instead of @apollo/client/core?

2021-12-16 08:13 UTC, Frodigo commented on packages/api-client/src/link.ts
> +} from '@apollo/client/core';
The same question as above (about @apollo/client)

2021-12-16 15:28 UTC, bloodf commented on package.json
> +    "yarn": "1.x"
No, because how Yarn 2+ handles the node_modules :(

There are still some configurations problems that need to be updated before.

2021-12-16 15:28 UTC, bloodf commented on packages/api-client/package.json
> +    "cross-fetch": "^3.1.4",
`cross-fetch` enables the usage of `fetch` everywhere. Preparing for future web IDEs usages :)

2021-12-16 21:53 UTC, bloodf commented on packages/api-client/src/helpers/magentoLink/graphQl.ts
> +} from '@apollo/client/core';
@Frodigo if we go with `@apollo/client` you are calling the React client. So we need to use the /core

2021-12-17 08:14 UTC, Frodigo approved these changes

2021-12-17 08:14 UTC, merged