bug: fix default billing information does not appear on address
vuestorefront/magento2 pull request #382
Opened 2022-01-06 13:09 UTC by KevinGorjan

Fix the missing text "default billing address"

## Description
Add information about default billing address next to the information about default shipping in address row
Reorganize the view and stand default shipping and default billing address above other addresses.

## Screenshots (if appropriate):
![image](https://user-images.githubusercontent.com/789614/148387854-c184fbf7-0cc0-4eb3-9e07-8b3fce6b72fb.png)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-01-06 16:50 UTC, bloodf submitted a review, later dismissed

2022-01-10 06:37 UTC, Frodigo requested changes
Hi @KevinGorjan, looks good to me, please only remove console.log that I mentioned earlier.

2022-01-10 08:37 UTC, KevinGorjan commented on packages/composables/src/getters/userAddressesGetters.ts
> +    console.log(addressesData);
done ✅

2022-01-10 08:44 UTC, Frodigo approved these changes

2022-01-10 08:44 UTC, merged