fix: expired user token
vuestorefront/magento2 pull request #392
Opened 2022-01-11 13:35 UTC by KevinGorjan

Fixes #198 

## Description
When the customer token is expired, it will log out the user and redirect the user to the home page.
A notification message will be displayed

## Related Issue

## Motivation and Context

## How Has This Been Tested?

* Create an account
* Log in to your account
* Enter your account (/my-account)
* Wait until the session is expired (by default this is 4h)
* When the customer token is expired, you will be redirected to the home page

## Screenshots (if appropriate):
![image](https://user-images.githubusercontent.com/789614/148952415-9b5246f6-3944-474b-9d8f-3c07ea6c74f8.png)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-01-11 14:25 UTC, Frodigo requested changes

2022-01-11 14:35 UTC, KevinGorjan commented on packages/theme/plugins/token-expired.js
> +      // ToDo :: Clear Cart items
No, I can’t complete this task because for some reason we can’t use composables in plugins or middlewares.
The application crashes.

2022-01-11 20:35 UTC, bloodf requested changes

2022-01-11 20:35 UTC, bloodf commented on packages/theme/components/LoginModal.vue
>              <div v-if="error.login">
```suggestion
            <div v-if="error.login">
```

2022-01-11 20:35 UTC, bloodf commented on packages/theme/plugins/token-expired.js
> +      // ToDo :: Clear Cart items
@Frodigo the problem with Composables in plugins is due to composition-api :(

Until Vue 3 is 100% we need to do some "gambiarras" 

Brazilian slang for those adaptations :P

2022-01-14 12:27 UTC, bartoszherba commented on packages/theme/composables/useUiNotification/index.ts
> +  const cookieMessage: UiNotification = app.$cookies.get(cookieNames.messageCookieName);
Can we translate this message? Or add improvement to translate all messages?

2022-01-14 12:27 UTC, bartoszherba commented on packages/theme/composables/useUiNotification/index.ts
> +  const cookieMessage: UiNotification = app.$cookies.get(cookieNames.messageCookieName);
Also, please add cookie message to a translation list in lang.

2022-01-14 12:28 UTC, bartoszherba commented on packages/theme/plugins/token-expired.js
> +export default ({ app, redirect }) => {
Can we write UT for this plugin?

2022-01-14 13:56 UTC, Frodigo commented on packages/theme/composables/useUiNotification/index.ts
> +  const cookieMessage: UiNotification = app.$cookies.get(cookieNames.messageCookieName);
Done

2022-01-14 14:33 UTC, Frodigo commented on packages/theme/plugins/token-expired.js
> +export default ({ app, redirect }) => {
Tests added.

2022-01-17 08:48 UTC, Frodigo approved these changes

2022-01-17 08:55 UTC, bartoszherba submitted a review, later dismissed

2022-01-17 10:18 UTC, Frodigo approved these changes

2022-01-17 10:18 UTC, Frodigo commented
Hi, @bloodf can you review this one again?

2022-01-18 04:54 UTC, merged