[WIP] fix(theme): out of stock product will no longer break cart
vuestorefront/magento2 pull request #404
Opened 2022-01-12 14:39 UTC by bartoszherba

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-01-13 09:29 UTC, Frodigo requested changes

2022-01-13 09:29 UTC, Frodigo commented on packages/theme/components/CartSidebar.vue
> +    const products = computed(() => cartGetters.getItems(cart.value).filter(Boolean));
You have already filtered items in composable
```suggestion
    const products = computed(() => cartGetters.getItems(cart.value);
```

2022-01-13 09:29 UTC, Frodigo commented on packages/theme/layouts/default.vue
> -        loadCart(),
So cart is loaded in different place, yeah?

2022-01-14 07:25 UTC, bartoszherba commented on packages/theme/layouts/default.vue
> -        loadCart(),
packages/theme/components/CartSidebar.vue:303

2022-01-14 07:26 UTC, bartoszherba commented on packages/theme/components/CartSidebar.vue
> +    const products = computed(() => cartGetters.getItems(cart.value).filter(Boolean));
Sometimes there is null inside, I was not able to track down where is the source.

2022-01-17 06:52 UTC, Frodigo requested changes

2022-01-17 06:52 UTC, Frodigo commented on packages/theme/components/__tests__/CartSidebar.spec.js
> +import stockStatusEnum from '~/enums/stockStatusEnum';
This is not used, please remove.

2022-01-17 06:52 UTC, Frodigo commented on packages/theme/components/__tests__/CartSidebar.spec.js
> +  describe('If the cart is empty', () => {
I know that we didn't talk about that, but the common pattern is to use one describe block for one test file. Could you refactor that?  

Besiedes, this is a good read about nesting: https://kentcdodds.com/blog/avoid-nesting-when-youre-testing

2022-01-17 06:52 UTC, Frodigo commented on packages/theme/components/__tests__/CartSidebar.spec.js
> +        const { queryByText } = render(CartSidebar);
```suggestion
        const { getByText } = render(CartSidebar);
```

2022-01-17 06:52 UTC, Frodigo commented on packages/theme/components/__tests__/CartSidebar.spec.js
> +        const closeSidebarBtn = queryByText('Go back shopping');
```suggestion
        const closeSidebarBtn = getByText('Go back shopping');
```

2022-01-17 06:52 UTC, Frodigo commented on packages/theme/components/__tests__/CartSidebar.spec.js
> +        expect(closeSidebarBtn).toBeTruthy();
```suggestion
        
```

2022-01-17 06:52 UTC, Frodigo commented on packages/theme/components/__tests__/CartSidebar.spec.js
> +        expect(uiStateMock.toggleCartSidebar.mock.calls).toHaveLength(1);
```suggestion
         expect(uiStateMock.toggleCartSidebar).toHaveBeenCalledTimes(1);
```

2022-01-17 06:54 UTC, Frodigo commented
There are some errors in console: 
![Screenshot 2022-01-17 at 07 53 47](https://user-images.githubusercontent.com/11998249/149721589-77111542-df1d-4ff6-807e-e91734a6e317.png)

2022-01-17 08:10 UTC, bartoszherba commented on packages/theme/components/CartSidebar.vue
> +                    class="color-danger sf-badge__absolute"
I did.

2022-01-17 08:25 UTC, Frodigo commented on packages/theme/components/CartSidebar.vue
> +                    class="color-danger sf-badge__absolute"
thank you

2022-01-17 08:35 UTC, bartoszherba commented on packages/theme/components/__tests__/CartSidebar.spec.js
> +  describe('If the cart is empty', () => {
I do not feel that the test is not readable or hard to understand, or code is hard to follow.
`<CartSidebar>
    ✓ should be not visible by default (17 ms)
    If the cart is empty
      And the cart sidebar is open
        ✓ should render empty state (23 ms)
        ✓ go back button must close the cart sidebar (42 ms)
    If the cart has two products
      ✓ should render two Product Cards (44 ms)
      ✓ should display proper total items value (37 ms)
      ✓ should render "go to checkout" button (35 ms)
      ✓ should render promo code input (27 ms)
      And exactly one product is out of stock
        ✓ should display exactly one out of stock badge (28 ms)`

2022-01-17 08:35 UTC, bartoszherba commented on packages/theme/components/__tests__/CartSidebar.spec.js
> +        const { queryByText } = render(CartSidebar);
Query eventually returns null and I want it not the error.

2022-01-17 08:35 UTC, bartoszherba commented on packages/theme/components/__tests__/CartSidebar.spec.js
> +        const closeSidebarBtn = queryByText('Go back shopping');
Query eventually returns null and I want it not the error.

2022-01-17 08:35 UTC, bartoszherba commented on packages/theme/components/__tests__/CartSidebar.spec.js
> +        expect(closeSidebarBtn).toBeTruthy();
I prefer explicit expectation, someone might not know by hearth how another tool is working in depth.

2022-01-17 08:35 UTC, bartoszherba commented on packages/theme/components/__tests__/CartSidebar.spec.js
> +        expect(uiStateMock.toggleCartSidebar.mock.calls).toHaveLength(1);
oki

2022-01-17 08:41 UTC, Frodigo commented on packages/theme/components/__tests__/CartSidebar.spec.js
> +        const { queryByText } = render(CartSidebar);
I see

2022-01-17 08:42 UTC, Frodigo commented on packages/theme/components/__tests__/CartSidebar.spec.js
> +        expect(closeSidebarBtn).toBeTruthy();
but `getByText` throws an error when the passed text does not exist in DOM, so the test will break then, the assertion is redundant.

2022-01-17 10:43 UTC, Frodigo approved these changes

2022-01-17 10:44 UTC, merged