fix: loosing data when moving between steps on the checkout
vuestorefront/magento2 pull request #440
Opened 2022-01-18 16:31 UTC by KevinGorjan

This ticket fixes 
* #410

## Description
The user can't navigate to any next page anymore, this can only be done when the form from the current step correctly is filled in.
If the user goes directly to the page by URL, the application will check of the previous step is valid, else the user will be redirected to the user-account page

## Related Issue
* #409  

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-01-19 06:01 UTC, Frodigo requested changes

2022-01-19 06:01 UTC, Frodigo commented on packages/theme/pages/Checkout/UserAccount.vue
> +        const data = checkout['user-account'];
I didn't see the logic for filling data in other steps. It's possible to do something like this in other steps as well?

2022-01-19 11:21 UTC, KevinGorjan commented on packages/theme/pages/Checkout/UserAccount.vue
> +        const data = checkout['user-account'];
On the shipping and billing step, the form gets the data when fetching the cart.

![image](https://user-images.githubusercontent.com/789614/150120290-6eb2e27e-3e9e-462d-b83d-289fa9cad78e.png)

That's why I don't store it in the localstorage.

2022-01-19 11:21 UTC, KevinGorjan commented on packages/theme/pages/Checkout/Payment.vue
> +      if (!checkout || !checkout.billing) {
Good idea, I'll add this ;-)

2022-01-24 08:29 UTC, KevinGorjan commented
@Frodigo I added tests for the asyncLocalStorage and the steps-helper for the checkout.

I didn't add tests in the pages because this will be done in a separate ticket

2022-01-24 08:46 UTC, Frodigo approved these changes

2022-01-24 08:46 UTC, merged