chore: updated dependencies & configuration management
vuestorefront/magento2 pull request #538
Opened 2022-02-01 20:24 UTC by bloodf

## Description
- created a dynamic `nuxt.config.js` configuration file based on you configuration, to enable `cloudnary` or `recaptcha`

`eslint`
- updated `eslint-plugin-unicorn` to `40.1.0`

`eslint-jest`
- updated `eslint-plugin-jest` to `26.0.0`

`eslint-typescript`
- `@typescript-eslint/eslint-plugin` to `5.10.2`
- `@typescript-eslint/parser` to `5.10.2`

`eslint-vue`
- updated `eslint-plugin-vue` to `8.4.0`

`api-client`
- updated `@apollo/client` to `3.5.8`
- updated `graphql` to `16.3.0`
- updated `cross-fetch` to `3.1.5`
- updated `typescript` to `4.5.5`
- updated `dotenv` to `15.0.0`
- updated `msw` to `0.36.8`

`theme`
- updated `isomorphic-dompurify` to `0.18.0`
- updated `@babel/core` to `7.16.12`
- updated `cypress` to `9.3.1`
- updated `dotenv` to `14.3.2`
- updated  `lint-staged` to `12.3.3`
- updated `mocha` to `9.2.0`
- updated `npm-check-updates` to `12.2.1`
- updated `typescript` to `4.5.5`

`repository`
- updated `@babel/core` to `7.16.12`
- updated `@babel/plugin-proposal-private-methods` to `7.16.11`
- updated `@commitlint/cli` to `16.1.0`
- updated `@graphql-codegen/cli` to `2.4.0`
- updated `@types/node` to `17.0.13`
- updated `@typescript-eslint/parser` to `5.10.1`
- updated `eslint` to `8.8.0`
- updated `npm-check-updates` to `12.2.1`
- updated `rollup` to `2.66.1`
- updated `vue-eslint-parser` to `8.2.0`
- updated  `@graphql-codegen/typescript-operations` to `2.2.3`
- updated  `@types/node` to `17.0.14`
- updated  `@typescript-eslint/parser` to `5.10.2`
- updated  `lint-staged` to `12.3.3`

## Related Issue

## Motivation and Context
Update the packages and make it easier to enable dynamic content based on configuration

## How Has This Been Tested?
locally tested

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2022-02-02 08:34 UTC, bartoszherba approved these changes

2022-02-02 08:35 UTC, Frodigo requested changes

2022-02-02 08:35 UTC, Frodigo commented on .github/workflows/deploy-vue-storefront-cloud.yml
> +          REDIS__PASSWORD: ${{ secrets.REDIS__PASSWORD }}
REDIS_PASSWORD is not necessary for our cloud. Redis is enabled only in the scope of the docker container as DevOps said.

2022-02-02 08:35 UTC, Frodigo commented on .vuestorefrontcloud/docker/Dockerfile
> +ARG REDIS__PASSWORD
As I mentioned above, please remove this arg also.

2022-02-02 08:35 UTC, Frodigo commented on .vuestorefrontcloud/docker/Dockerfile
> +ENV REDIS__PASSWORD=${REDIS__PASSWORD}
Please remove

2022-02-02 08:35 UTC, Frodigo commented on .vuestorefrontcloud/docker/Dockerfile
> +RUN npx yarn@1.19.0 workspace @vue-storefront/magento-theme add @sentry/tracing @nuxtjs/sentry @vsf-enterprise/redis-cache
good solution, thanks!

2022-02-02 08:35 UTC, Frodigo commented on packages/theme/.env.example
> -MAGENTO_BASE_URL={YOUR_SITE_FRONT_URL}
Can explain why you remove it?

2022-02-02 13:32 UTC, bloodf commented on packages/theme/.env.example
> -MAGENTO_BASE_URL={YOUR_SITE_FRONT_URL}
duplicate :)

2022-02-02 13:32 UTC, bloodf commented on .vuestorefrontcloud/docker/Dockerfile
> +RUN npx yarn@1.19.0 workspace @vue-storefront/magento-theme add @sentry/tracing @nuxtjs/sentry @vsf-enterprise/redis-cache
:)

2022-02-02 13:34 UTC, bloodf commented on .github/workflows/deploy-vue-storefront-cloud.yml
> +          REDIS__PASSWORD: ${{ secrets.REDIS__PASSWORD }}
done ✅

2022-02-03 07:36 UTC, Frodigo approved these changes

2022-02-03 07:36 UTC, merged