refactor: refactored useExternalCheckout composable
vuestorefront/magento2 pull request #571
Opened 2022-02-07 19:51 UTC by Frodigo

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-02-07 20:01 UTC, bartoszherba requested changes

2022-02-07 20:01 UTC, bartoszherba commented on packages/composables/src/index.ts
> -export { default as useExternalCheckout } from './composables/useExternalCheckout';
Maybe mark as deprecated instead, eg i use
```
/**
 * @deprecated since version <version?>
 *
 * @see <add docs link>
 */
```
So we can remove it later at some point to not break other's apps. If someone is using this composable for example

2022-02-08 06:55 UTC, bartoszherba commented on packages/theme/composables/useExternalCheckout/useExternalCheckout.ts
> +    loading: readonly(loading),
Readonly unwrap REF so you will be not able to do something like loading.value in code, is this what you want?

2022-02-08 06:59 UTC, Frodigo commented on packages/theme/composables/useExternalCheckout/useExternalCheckout.ts
> +    loading: readonly(loading),
I see, no

2022-02-08 08:29 UTC, Frodigo commented
@bartoszherba this is ready for re-review

2022-02-08 08:38 UTC, bartoszherba approved these changes

2022-02-08 08:44 UTC, merged