refactor(theme): refactor useConfig composable
vuestorefront/magento2 pull request #572
Opened 2022-02-07 20:12 UTC by bartoszherba

## Description
    - mark composable useConfig as deprecated
    - move composable to theme module
    - rework composable to get rid of core dependency and to utilize Pinia store

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-02-07 20:41 UTC, Frodigo requested changes

2022-02-07 20:41 UTC, Frodigo commented on packages/theme/composables/useConfig/index.ts
> +    loading,
what do you think about wrapping this by `readonly` from composition API?

2022-02-07 20:41 UTC, Frodigo commented on packages/theme/composables/useConfig/index.ts
> +    config: computed(() => configStore.value),
Does it need to be computed?

2022-02-08 08:21 UTC, bartoszherba commented on packages/theme/composables/useConfig/index.ts
> +    config: computed(() => configStore.value),
Otherwise, it will break the interface and I will have to update types and logic in other places. For now let it be.

2022-02-08 08:32 UTC, merged