feat: asset optimization
vuestorefront/magento2 pull request #628
Opened 2022-02-18 14:31 UTC by AlexanderDevitsky

## Description

## Related Issue

https://github.com/vuestorefront/magento2/issues/397
https://vsf.atlassian.net/browse/M2-45

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-02-18 16:11 UTC, Frodigo requested changes

2022-02-18 16:11 UTC, Frodigo commented on packages/theme/components/AppHeader.vue
> +              @click="isSearchOpen ? isSearchOpenx = false : isSearchOpen = true"
`isSearchOpenx` Looks like a typo mistake

2022-02-18 16:11 UTC, Frodigo commented on packages/theme/components/General/IconSprite.vue
> +    <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 231 221.4210525" id="logo">
Today we updated the logo, please double-check if this is a new one https://github.com/vuestorefront/magento2/pull/622

2022-02-18 16:23 UTC, AlexanderDevitsky commented on packages/theme/components/AppHeader.vue
> +              @click="isSearchOpen ? isSearchOpenx = false : isSearchOpen = true"
@Frodigo Fixed

2022-02-23 07:53 UTC, Frodigo approved these changes
@AlexanderDevitsky looks good to me. Please resolve conflicts, then I will merge it and we will be able to test your solution on our servers. 

Thanks,
Marcin

2022-02-23 12:54 UTC, AlexanderDevitsky commented
@Frodigo resolved

2022-02-23 14:38 UTC, merged