feat: migrate to ESM and esbuild
vuestorefront/magento2 pull request #677
Opened 2022-03-01 10:51 UTC by filipsobol

2022-03-01 11:13 UTC, Frodigo requested changes

2022-03-01 11:13 UTC, Frodigo commented on packages/composables/package.json
> +    "@vue-storefront/core": "link:/home/fsobol/Projects/Storefront/packages/core",
Looks like a mistake, please undo this change.

2022-03-01 11:13 UTC, Frodigo commented on packages/theme/package.json
> +    "@vue-storefront/cache": "link:/home/fsobol/Projects/Storefront/packages/cache",
Same in this file

2022-03-03 14:23 UTC, Frodigo submitted a review, later dismissed

2022-03-04 14:01 UTC, sethidden commented on packages/api-client/package.json
> +    "dev": "yarn dev:package & yarn dev:server",
Wondering if this works on Windows? Asking because of the I think UNIX-only "&" syntax
---
Won't this also cause a zombie node process if you CTRL+C in the terminal (only the process in the foreground will be killed, no)? You can easily check this by doing something like `npm install & npm install` - if you ctrl C, you'll still see output from the 2nd process

Guess you could use https://www.npmjs.com/package/npm-run-all or some yarn builtin if it exists (I'm an NPM man myself)

2022-03-04 14:40 UTC, filipsobol commented on packages/api-client/package.json
> +    "dev": "yarn dev:package & yarn dev:server",
That's an excellent point! I fixed it in https://github.com/vuestorefront/magento2/pull/677/commits/846b00a400830ee5f081ee7bad15a29e93b600d0

2022-03-07 15:20 UTC, sethidden commented
LGTM, I'll talk to Marcin tomorrow about this

2022-03-08 06:55 UTC, sethidden approved these changes

2022-03-08 07:33 UTC, Frodigo approved these changes

2022-03-08 07:33 UTC, merged