refactor(theme): refactored useUpsellProducts composable
vuestorefront/magento2 pull request #738
Opened 2022-03-16 08:36 UTC by Frodigo

## Description
- added useUpsellProducts composable to theme
- made useUpsellProducts composable and factory from integration package depracated
- refactored UpsellProducts component
- fixed SSR issues on product page

## Related Issue
[#256](https://vsf.atlassian.net/browse/M2-256)

## Motivation and Context
refactorization, improving performance and developer experience

## How Has This Been Tested?
Tested on my local in production mode

## Screenshots (if appropriate):
![Screenshot 2022-03-16 at 09 36 00](https://user-images.githubusercontent.com/11998249/158549390-4114eb71-57a3-4947-a6d0-9d13b92d88dd.png)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2022-03-16 15:16 UTC, bartoszherba requested changes

2022-03-16 15:16 UTC, bartoszherba commented on packages/theme/composables/useUpsellProducts/index.ts
> +export const useUpsellProducts = (): UseUpsellProductsInterface => {
We cannot use composables like that, with useContext inside because then composing these composables will yield error that some function must be used in the setup. I suggest to add context as a factory param and remove useContext from composable. Please, check https://github.com/vuestorefront/magento2/pull/742 eg. useCart

2022-03-16 15:16 UTC, bartoszherba commented on packages/theme/composables/useUpsellProducts/index.ts
> +      results = data.products?.items[0]?.upsell_products;
If results can be null then Promise<Array<UpsellProducts>> is not true, try to wrap it with Maybe type, or set default value to an empty array.

2022-03-17 08:19 UTC, sethidden commented on packages/theme/composables/useUpsellProducts/index.ts
> +export const useUpsellProducts = (): UseUpsellProductsInterface => {
As heads up: Marcin linked me to here in useReview, but I ended up not adding it for now as we're still figuring it out.

2022-03-17 08:21 UTC, sethidden commented on packages/theme/composables/useUpsellProducts/index.ts
> +      results = data.products?.items[0]?.upsell_products;
If my useReview PR gets added i've added the context.d.ts types there which should add real types to this line (just you'll have to rebase from develop)

2022-03-17 08:27 UTC, bartoszherba commented on packages/theme/composables/useUpsellProducts/useUpsellProducts.d.ts
> +import {
I was talking about UpsellProductsQuery

2022-03-17 12:04 UTC, bartoszherba requested changes

2022-03-17 12:04 UTC, bartoszherba commented on packages/theme/composables/useUpsellProducts/index.ts
> +import {Maybe} from "~/composables/types";
```suggestion
import { Maybe, ComposableFunctionArgs } from "~/composables/types";
```

2022-03-17 12:04 UTC, bartoszherba commented on packages/theme/composables/useUpsellProducts/index.ts
> +import { ComposableFunctionArgs, ProductsSearchParams, Logger } from '@vue-storefront/core';
```suggestion
import { ProductsSearchParams, Logger } from '@vue-storefront/core';
```

2022-03-17 12:04 UTC, bartoszherba commented on packages/theme/composables/useUpsellProducts/index.ts
> +  const loading: Ref<boolean> = ref(false);
```suggestion
  const loading  = ref(false);
```

2022-03-17 12:38 UTC, Frodigo commented on packages/theme/composables/useUpsellProducts/useUpsellProducts.d.ts
> +} from '~/modules/GraphQl/types';
```suggestion
} from '~/modules/GraphQL/types';
```

2022-03-18 06:57 UTC, bartoszherba submitted a review, later dismissed

2022-03-18 07:33 UTC, bartoszherba approved these changes

2022-03-18 07:36 UTC, merged