refactor: refactored the useApi composable
vuestorefront/magento2 pull request #760
Opened 2022-03-21 13:13 UTC by Frodigo

## Description
The first step of the useApi composable refactoring:

## Motivation and Context
providing better developer experience and open opportunity to use the useApi composable to query data in more generic way.

## How Has This Been Tested?
tested on my local env

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2022-03-21 13:44 UTC, sethidden requested changes
I think this approach creates an additional level of abstraction (in the form of the `request` without offering much benefit in return. query and mutate are `request`s on their own, I don't think there's a reason to wrap them like that.

What are the problems with the current implementation?

I understand the request() and the switch is made to not to double the error.value and loading.value assignments but as a side effect, but here I'd really just prefer the duplication (not all duplication is bad) like we have in all the other composables we've ported (error.value repeating a lot etc)

---

I'm not super keen on keeping the useApi composable tbh, I'd much prefer to leave it as is for now. This is a thing that seems like it'd be best to discuss in a meeting, add it to the backlog, measure it on the refinement etc.

2022-03-22 07:41 UTC, Frodigo commented
> I think this approach creates an additional level of abstraction (in the form of the `request` without offering much benefit in return. query and mutate are `request`s on their own, I don't think there's a reason to wrap them like that.
> 
> What are the problems with the current implementation?

Current implementation of useApi itself is ok, but that changes resolves other problem. 

Now, we have ~ 35 composables in theme/composables directory, and a lot of them are redundant because the only change that is dynamic there is a graphql query. 

Typically there are three fields:
- error
- loading
- load or search

So we are repeating code as monkeys, and the difference is only the name of composable (for example useRelatedProducts, useUpsellProducts, useCategory, useCategoryContent and so on)

We can delegate that logic to useApi, and remove redundant composables. I wanted to do that in the next step. 

On the other hand, we need to maintain that redundant composables code and if we had wanted to cover composables by unit tests we would have to repeat ourselves again in tests. In the new approach we have less code, fewer tests, and fewer places to maintain.

> 
> I understand the request() and the switch is made to not to double the error.value and loading.value assignments but as a side effect, but here I'd really just prefer the duplication (not all duplication is bad) like we have in all the other composables we've ported (error.value repeating a lot etc)

Composables you mentioned are not using this useApi composable. Those composables use API client from `@vue-storefront/magento-api. 

In next step we would refactor composables to new API, and avoid duplications.

> 
> I'm not super keen on keeping the useApi composable tbh, I'd much prefer to leave it as is for now. This is a thing that seems like it'd be best to discuss in a meeting, add it to the backlog, measure it on the refinement etc then do it in an organized way like we've done with the composables
> 
> I'm thinking this refactor could be better if request() took a function that returns a promise as first argument instead of the switch statement

I don't understand. The request function purpose is to send a query or mutation and prepare correct request parameters. I created the request function only because I didn't want to repeat code in both query and mutate functions. 

The switch statement is only for deciding which graphql operation should be sent: query or mutation, moreover the request function is private.

2022-03-22 07:49 UTC, sethidden commented
@Frodigo Down the line, I think using useApi for the error.value and loading.value logic is ok as it reduces the code duplication you mentioned, but adding `request` which wraps `query` and `mutation` shouldn't be included here, as `query` and `mutation` and cookies etc. shouldn't be in `useApi` in the first place (need to move cookies out of context etc). So to me it's necessary to take 2 steps back to take the step you want to take here

Let's see what comes out of our call soon :P

2022-03-22 07:55 UTC, Frodigo commented
> @Frodigo Down the line, I think using useApi for the error.value and loading.value logic is ok as it reduces the code duplication you mentioned, but adding `request` which wraps `query` and `mutation` shouldn't be included here, as `query` and `mutation` and cookies etc. shouldn't be in `useApi` in the first place (need to move cookies out of context etc). So to me it's necessary to take 2 steps back to take the step you want to take here
> 
> Let's see what comes out of our call soon :P

So you would remove cookies state from the useApi composable? 

As I mentioned before the `request` method is private and it's only for remove code duplication in query and mutate functions. I didn't want to repeat things like params creation and try catch block, logging etc.

Without request function code would look like this:


```
const mutate = <TYPE, VARIABLES>(requestParams: RequestParams<VARIABLES>, type: string): Promise<TYPE> => {
    const params: RequestParams<VARIABLES> = {
      variables: null,
      endpoint: defaultEndpoint,
      requestHeaders: defaultHeaders,
      debugInfo: '',
      ...requestParams,
    };
    let response = null;

    try {
      Logger.debug(`[Magento] ${params.debugInfo}`, { params });
      loading.value = true;

      response =  graphQLRequest<TYPE, VARIABLES>(params.endpoint, params.document, params.variables, params.requestHeaders);

      Logger.debug(`[Magento] ${params.debugInfo} – results: `, { response });
    } catch (err) {
      error.value = err;
      Logger.error(`[Magento] ${params.debugInfo} – error: `, { response });
    } finally {
      loading.value = false;
    }

    return response;
  };


const query = <TYPE, VARIABLES>(requestParams: RequestParams<VARIABLES>, type: string): Promise<TYPE> => {
    const params: RequestParams<VARIABLES> = {
      variables: null,
      endpoint: defaultEndpoint,
      requestHeaders: defaultHeaders,
      debugInfo: '',
      ...requestParams,
    };
    let response = null;

    try {
      Logger.debug(`[Magento] ${params.debugInfo}`, { params });
      loading.value = true;

      response = new GraphQLClient(params.endpoint, {
            method: useGETForQueries ? 'GET' : 'POST',
            headers: params.requestHeaders,
          }).request<TYPE, VARIABLES>(params.document, params.variables);

      Logger.debug(`[Magento] ${params.debugInfo} – results: `, { response });
    } catch (err) {
      error.value = err;
      Logger.error(`[Magento] ${params.debugInfo} – error: `, { response });
    } finally {
      loading.value = false;
    }

    return response;
  };
```

2022-03-22 07:57 UTC, bartoszherba requested changes

2022-03-22 07:57 UTC, bartoszherba commented on packages/theme/composables/useApi/index.ts
> +  variables?: VARIABLES | null,
is the "or NULL" REALLY important to have? If not passed it will be falsy anyway

2022-03-22 07:57 UTC, bartoszherba commented on packages/theme/composables/useApi/index.ts
> +  const request = <TYPE, VARIABLES>(requestParams: RequestParams<VARIABLES>, type: string): Promise<TYPE> => {
```suggestion
  const request = <TYPE, VARIABLES>(requestParams: RequestParams<VARIABLES>, type: string = GraphQLOperation.query): Promise<TYPE> => {
```

2022-03-22 07:57 UTC, bartoszherba commented on packages/theme/composables/useApi/index.ts
> +        }
```suggestion
```

2022-03-22 07:57 UTC, bartoszherba commented on packages/theme/composables/useApi/index.ts
> +      variables: null,
Field is not required
```suggestion
```

2022-03-22 07:57 UTC, bartoszherba commented on packages/theme/composables/useApi/index.ts
> +      debugInfo: '',
Field is not required
```suggestion
```

2022-03-22 07:57 UTC, bartoszherba commented on packages/theme/composables/useApi/index.ts
> +import { useContext, ref } from '@nuxtjs/composition-api';
In general. I think that API client do not have to utilize composition api so it will not share more technical debt than necessary. Eg. loading or errors as ref are not really required. Loading can be easily handled by the client and error can be simply thrown so the client can handle it. This is not a big thing maybe, just the less debt risk the better.

2022-03-22 08:04 UTC, Frodigo commented on packages/theme/composables/useApi/index.ts
> +import { useContext, ref } from '@nuxtjs/composition-api';
Good point,

so let me understand correctly that:
1. Instead of a return error that is a Ref, return a plain error? 
2. loading field is not necessary here, we remove it, and components, when useApi is used, takes care of handle loading state?

2022-03-22 08:07 UTC, Frodigo commented on packages/theme/composables/useApi/index.ts
> +import { useContext, ref } from '@nuxtjs/composition-api';
@bartoszherba  In addition to point 1. Maybe we can just throw an error instead of returning an error field? cc: @sethidden

2022-03-22 08:29 UTC, sethidden requested changes
Let's talk about this on the daily meeting

2022-03-22 08:32 UTC, sethidden commented on packages/theme/composables/useApi/index.ts
> +import { useContext, ref } from '@nuxtjs/composition-api';
If error and loading weren't refs then using useApi would be no different than axios.get()

e.g. loading is a good example - why litter the template with const isXLoading = ref(false), const isYLoading = ref(false) if that can be returned from an useApi? Perhaps Bartek is talking about a different form of useApi (I'm talking about the "simple promise helper" form)

2022-04-04 07:41 UTC, sethidden commented
<img width="1034" alt="image" src="https://user-images.githubusercontent.com/5359825/161496426-826ac759-abfb-490a-a87a-da3369a846da.png">
Would it make sense to just use config.get instead of this? This would further detach useApi from the context.

At this point $magento.config is a redundant extra layer of abstraction over just what we have in config.get. I guess it's ok for useApi to still use config.get or CookiesUniversal.get (instead of $magento.config.state.get[CookieName]) even if this is inconsistent - independence from context is king

2022-04-04 09:31 UTC, Frodigo commented
> <img alt="image" width="1034" src="https://user-images.githubusercontent.com/5359825/161496426-826ac759-abfb-490a-a87a-da3369a846da.png">
> 
> Would it make sense to just use config.get instead of this? This would further detach useApi from the context.
> At this point $magento.config is a redundant extra layer of abstraction over just what we have in config.get. I guess it's ok for useApi to still use config.get or CookiesUniversal.get (instead of $magento.config.state.get[CookieName]) even if this is inconsistent - independence from context is king

I tried to use cookie CookiesUniversal.get but app crashed then. 

Here is the code snippet: 

```
import Cookie from 'cookie-universal';
import { request as graphQLRequest, GraphQLClient } from 'graphql-request';
import cookieNames from '~/enums/cookieNameEnum';

export type RequestParams<VARIABLES> = {
  document: string,
  variables?: VARIABLES | null,
  endpoint?: string,
  requestHeaders?: {
    authorization?: string,
    store?: string
  },
  debugInfo?: string
};

const defaultEndpoint = process.env.MAGENTO_GRAPHQL;

const buildParams = <VARIABLES>(requestParams: RequestParams<VARIABLES>): RequestParams<VARIABLES> => {
  const defaultHeaders: {
    authorization?: string,
    store?: string
  } = {};

  const cookies = Cookie();
  const customerToken = cookies.get(cookieNames.customerCookieName);
  const storeCode = cookies.get(cookieNames.storeCookieName);

  if (customerToken) {
    defaultHeaders.authorization = `Bearer ${customerToken}`;
  }

  if (storeCode) {
    defaultHeaders.store = storeCode;
  }

  return {
    endpoint: defaultEndpoint,
    requestHeaders: {
      ...defaultHeaders,
      ...requestParams.requestHeaders,
    },
    ...requestParams,
  };
};

export const mutate = <TYPE, VARIABLES>(requestParams: RequestParams<VARIABLES>): Promise<TYPE> => {
  const params = buildParams<VARIABLES>(requestParams);

  return graphQLRequest<TYPE, VARIABLES>(params.endpoint, params.document, params.variables, params.requestHeaders);
};

export const query = <TYPE, VARIABLES>(requestParams: RequestParams<VARIABLES>): Promise<TYPE> => {
  const params = buildParams<VARIABLES>(requestParams);
  console.log(requestParams);

  return new GraphQLClient(params.endpoint, {
    method: 'GET',
    headers: params.requestHeaders,
  }).request<TYPE, VARIABLES>(params.document, params.variables);
};
```

2022-04-12 12:27 UTC, closed without merging