chore: remove @vue-storefront/magento dependency from theme
vuestorefront/magento2 pull request #770
Opened 2022-03-22 12:13 UTC by sethidden

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-03-22 12:15 UTC, sethidden commented on package.json
>      "internals/*"
it'd make sense to remove the `*` and just write `packages/theme/ and `packages/magento-api`

2022-03-22 13:36 UTC, sethidden commented
@Frodigo [it'd make sense to deprecate the published @vue-storefront/package on NPM](https://docs.npmjs.com/deprecating-and-undeprecating-packages-or-package-versions) - do you know somebody who can do that?

2022-03-23 05:29 UTC, Frodigo requested changes

2022-03-23 05:29 UTC, Frodigo commented on package.json
> +    "packages/theme",
It's not necessary because people do not use this repository, they use `template-magento` repository where packages/theme is a root. So these workspaces are useful only for us. Please restore this change.

2022-03-23 07:10 UTC, bartoszherba submitted a review, later dismissed

2022-03-23 07:32 UTC, Frodigo approved these changes

2022-03-23 07:55 UTC, merged