refactor: unify cookie retrieval
vuestorefront/magento2 pull request #797
Opened 2022-03-30 07:35 UTC by sethidden

2022-03-31 08:56 UTC, sethidden commented on packages/api-client/src/helpers/apiClient/defaultSettings.ts
> +    // @ts-ignore
I can't get TS to be quiet about this. This is not an important file as it's just the defaultSettings and a function that returns void

2022-03-31 10:00 UTC, Frodigo commented on packages/theme/composables/useUiNotification/index.ts
> +      app.$vsf.$magento.config.state.setMessage();
there is no method removeMessage? It's not clear to me that `setMessage()` clears cookie.

2022-03-31 13:07 UTC, sethidden commented on packages/theme/composables/useMagentoConfiguration.ts
> +        // @ts-ignore
I added generics now so I could remove the ts-ignores and leave a comment that those types aren't entirely correct

2022-04-01 12:30 UTC, sethidden commented on packages/theme/composables/useUiNotification/index.ts
> +      app.$vsf.$magento.config.state.setMessage();
@Frodigo Hmm, I recently moved the setMessage getMessage and removeMessage methods to one container so now it's config.state.message.set .get and .remove, but that makes it necessary to introduce breaking changes into magento-api.

Is it ok to keep the old approach of having setMessage, getMessage and removeMessage on the top level? So ~18 methods in one container. It's pretty verbose and not very fun but I'd like to avoid messing a lot of magento-api types to reduce the damage of migrating from rc6 to rc7 for example.

2022-04-01 13:58 UTC, sethidden commented on packages/theme/composables/useMagentoConfiguration.ts
> +        // @ts-ignore
nope

2022-04-01 14:01 UTC, sethidden commented on packages/theme/composables/useUiNotification/index.ts
> +      app.$vsf.$magento.config.state.setMessage();
/\ Done what I said above

2022-04-01 14:18 UTC, sethidden commented on packages/theme/composables/useMagentoConfiguration.ts
> +      if (!app.$vsf.$magento.config.state.getStore() || updateCookies) {
There's something wrong with the 3 ifs here. They're making the app send serialized objects inside cookies instead of regular string values

2022-04-01 14:20 UTC, sethidden commented on packages/theme/composables/useMagentoConfiguration.ts
> +      if (!app.$vsf.$magento.config.state.getStore() || updateCookies) {
Facepalm i removed the getters

2022-04-04 07:20 UTC, Frodigo commented
@sethidden please provide a description for this pull request.

2022-04-04 07:23 UTC, sethidden commented
@Frodigo is this ok?

2022-04-04 07:24 UTC, Frodigo requested changes

2022-04-04 07:24 UTC, Frodigo commented on packages/theme/plugins/token-expired.ts
> +    app.router.push(app.localePath('/'));
Can you explain this change?

2022-04-04 07:25 UTC, Frodigo commented
> @Frodigo is this ok?

yes, thanks!

2022-04-04 07:26 UTC, sethidden commented
https://router.vuejs.org/api/#go <https://router.vuejs.org/api/#go> go takes a number as argument, not a string

> On 4 Apr 2022, at 09:24, Marcin Kwiatkowski ***@***.***> wrote:
> 
> 
> @Frodigo requested changes on this pull request.
> 
> In packages/theme/plugins/token-expired.ts <https://www.google.com/url?q=https://github.com/vuestorefront/magento2/pull/797%23discussion_r841435404&source=gmail-imap&ust=1649661881000000&usg=AOvVaw1ePKgYPhCnm651qz0Nb60->:
> 
> >        type: 'warning',
>        icon: null,
>        persist: true,
>        title: null,
>      });
>  
> -    app.router.go(app.localePath('/'));
> +    app.router.push(app.localePath('/'));
> Can you explain this change?
> 
> —
> Reply to this email directly, view it on GitHub <https://www.google.com/url?q=https://github.com/vuestorefront/magento2/pull/797%23pullrequestreview-929929923&source=gmail-imap&ust=1649661881000000&usg=AOvVaw2lf5ZlGs7345wOo_K0mDFz>, or unsubscribe <https://www.google.com/url?q=https://github.com/notifications/unsubscribe-auth/ABI4RUJVCZ5LXIGVZ6IGRDTVDKKLJANCNFSM5SA7MNBQ&source=gmail-imap&ust=1649661881000000&usg=AOvVaw2MwbyeLwUgrWS6dq2Esgec>.
> You are receiving this because you were mentioned.
>

2022-04-04 07:28 UTC, sethidden commented
(Sending again because email responses to gh notifications got broken)
https://router.vuejs.org/api/#go <https://router.vuejs.org/api/#go> takes a number as argument, not a string

> On 4 Apr 2022, at 09:24, Marcin Kwiatkowski ***@***.***> wrote:
> 
> 
> @Frodigo requested changes on this pull request.
> 
> In packages/theme/plugins/token-expired.ts <https://www.google.com/url?q=https://github.com/vuestorefront/magento2/pull/797%23discussion_r841435404&source=gmail-imap&ust=1649661881000000&usg=AOvVaw1ePKgYPhCnm651qz0Nb60->:
> 
> >        type: 'warning',
>        icon: null,
>        persist: true,
>        title: null,
>      });
>  
> -    app.router.go(app.localePath('/'));
> +    app.router.push(app.localePath('/'));
> Can you explain this change?
> 
> —
> Reply to this email directly, view it on GitHub <https://www.google.com/url?q=https://github.com/vuestorefront/magento2/pull/797%23pullrequestreview-929929923&source=gmail-imap&ust=1649661881000000&usg=AOvVaw2lf5ZlGs7345wOo_K0mDFz>, or unsubscribe <https://www.google.com/url?q=https://github.com/notifications/unsubscribe-auth/ABI4RUJVCZ5LXIGVZ6IGRDTVDKKLJANCNFSM5SA7MNBQ&source=gmail-imap&ust=1649661881000000&usg=AOvVaw2MwbyeLwUgrWS6dq2Esgec>.
> You are receiving this because you were mentioned.
>

2022-04-04 07:30 UTC, sethidden commented on packages/theme/plugins/token-expired.ts
> +    app.router.push(app.localePath('/'));
https://router.vuejs.org/api/#go takes a number as argument, not string

2022-04-04 07:36 UTC, Frodigo commented on packages/theme/plugins/token-expired.ts
> +    app.router.push(app.localePath('/'));
Thanks!

2022-04-04 07:36 UTC, Frodigo approved these changes

2022-04-04 07:36 UTC, merged