docs: generate composables doc from jsdoc comments
vuestorefront/magento2 pull request #800
Opened 2022-03-31 09:05 UTC by filipsobol

2022-04-05 06:54 UTC, sethidden commented on docs/package.json
> +    "theme-ref": "cd ../scripts && node generateReference.mjs",
```suggestion
    "theme-ref": "cd ../scripts && node generateApiReference.mjs",
```

2022-04-05 06:54 UTC, sethidden commented on docs/package.json
> +    "api-extract": "rimraf api-reference && yarn api-ref && yarn theme-ref && yarn ref-md",
optional: if possible, run rimraf as part of generateApiReference

2022-04-05 06:54 UTC, sethidden commented on packages/api-client/src/api/cmsBlocks/index.ts
> + * @returns Promise<ApolloQueryResult<CmsBlockQuery>>
```suggestion
```
Is it possible for the docs to infer the TS type from the code? It feels redundant to double it up if it already exists in the code

Something like the jsdoc hover does here - it knows the return type is string already
<img width="255" alt="image" src="https://user-images.githubusercontent.com/5359825/161695635-7a2fbac2-0015-439d-b874-58020820a0c4.png">

2022-04-05 06:54 UTC, sethidden commented on packages/api-client/src/api/cmsBlocks/index.ts
> + * @param customQuery - (optional) - custom GraphQL query that extends the default cmsBlocks query
```suggestion
 * @param [customQuery] - custom GraphQL query that extends the default cmsBlocks query
```
https://jsdoc.app/tags-param.html#optional-parameters-and-default-values

2022-04-05 06:57 UTC, Frodigo commented on packages/api-client/src/api/cmsBlocks/index.ts
> + * @param customQuery - (optional) - custom GraphQL query that extends the default cmsBlocks query
thanks for the link, but keep in mind that we don't use jsdoc. We use https://api-extractor.com/pages/setup/invoking/

2022-04-05 06:58 UTC, Frodigo commented on packages/api-client/src/api/cmsBlocks/index.ts
> + * @returns Promise<ApolloQueryResult<CmsBlockQuery>>
I will check that.

2022-04-05 06:59 UTC, sethidden commented on packages/api-client/src/api/cmsBlocks/index.ts
> + * @returns Promise<ApolloQueryResult<CmsBlockQuery>>
Isn't that the point of api-extractor anyways ie. extracting TS types as docs? https://api-extractor.com/pages/tsdoc/tag_param/

` For TypeScript source code, the parameter type information is already fully expressed in the code, and thus it would be redundant to try to express it in a doc comment.`

2022-04-05 07:00 UTC, Frodigo commented on docs/package.json
> +    "theme-ref": "cd ../scripts && node generateReference.mjs",
Added.

2022-04-05 07:00 UTC, sethidden commented on packages/api-client/src/api/cmsBlocks/index.ts
> + * @param customQuery - (optional) - custom GraphQL query that extends the default cmsBlocks query
The optionality information is in TypeScript anyways so perhaps it makes sense to just textually describe the param, without any extra info

2022-04-05 07:40 UTC, Frodigo commented on packages/api-client/src/api/cmsBlocks/index.ts
> + * @returns Promise<ApolloQueryResult<CmsBlockQuery>>
Ok. it works, I removed redundant declarations.

2022-04-05 07:45 UTC, Frodigo commented on packages/api-client/src/api/cmsBlocks/index.ts
> + * @param customQuery - (optional) - custom GraphQL query that extends the default cmsBlocks query
I checked and it doesn't work so I can't change that.

2022-04-05 07:49 UTC, Frodigo approved these changes

2022-04-05 08:59 UTC, sethidden commented on packages/api-client/src/api/cmsBlocks/index.ts
> + * @param customQuery - (optional) - custom GraphQL query that extends the default cmsBlocks query
@Frodigo can you just change it to without "(optional)"? If the return type can be inferred then the fact that the argument is optional should be too

2022-04-05 09:16 UTC, bartoszherba commented on packages/api-client/src/api/cmsBlocks/index.ts
> + * @param customQuery - (optional) - custom GraphQL query that extends the default cmsBlocks query
TS can infer if an argument is optional but the doc generator or the reading user - can't. I want to know if something is optional BEFORE I event starts to write the code.

2022-04-05 09:16 UTC, bartoszherba approved these changes

2022-04-05 09:18 UTC, sethidden commented on packages/api-client/src/api/cmsBlocks/index.ts
> + * @param customQuery - (optional) - custom GraphQL query that extends the default cmsBlocks query
No, I mean since it could infer the return type in a way that Marcin felt is acceptable, I'm wondering if the same can happen for the argument

2022-04-06 06:45 UTC, Frodigo commented on packages/api-client/src/api/cmsBlocks/index.ts
> + * @param customQuery - (optional) - custom GraphQL query that extends the default cmsBlocks query
Return type is easy to see without docs annotation, but the optional argument isn't clear without that so I recommend to keep that information.

2022-04-06 06:46 UTC, sethidden requested changes
@filipsobol mind squashing the commits (either to 1 commit or 2-3 for organization's sake if you prefer)? To avoid ~10 changelog entries like docs: update

2022-04-06 06:56 UTC, Frodigo approved these changes

2022-04-06 07:43 UTC, filipsobol commented
> @filipsobol mind squashing the commits (either to 1 commit or 2-3 for organization's sake if you prefer)? To avoid ~10 changelog entries like docs: update

PR is squashed when merging, and GH allows changing the message and description. Isn't that an easier way?

2022-04-06 07:47 UTC, sethidden commented
@filipsobol we have two merging options available - rebase and squash. It's possible to accidentally rebase (if e.g. the last time you merged  a PR you rebased, that option becomes default in GitHub) and make some overly verbose changelog entries.

Squash is preferred for PRs and rebase is preferred for release merges, so this is why we have two. GitHub does not allow chaning merge policy per branch unfortunately. I'd also prefer if squash were the only possible option, so that people can avoid having to learn `git rebase --interactive`

2022-04-06 07:49 UTC, sethidden approved these changes

2022-04-06 07:57 UTC, merged