M2 187 breadcrumbs
vuestorefront/magento2 pull request #819
Opened 2022-04-06 10:58 UTC by sethidden

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-04-06 10:59 UTC, sethidden commented on packages/theme/modules/catalog/category/components/breadcrumbs/CategoryBreadcrumbs.vue
> +      // TODO do not hardcode 'default' as this store URL can change, add some stripStore helper
Also to apply in CategorySidebar

2022-04-06 11:01 UTC, sethidden commented on packages/theme/modules/catalog/pages/default.vue
> +      <CategoryBreadcrumbs />
This component should definitely have props but I need to add some logic sharing between MobileCategorySidebar and the new CategoryBreadcrumbs since their logic is pretty much the same.

I'll probably make some composable

2022-04-06 11:02 UTC, sethidden commented on packages/theme/modules/catalog/pages/default.vue
> -.breadcrumbs {
Was unused

2022-04-06 11:03 UTC, sethidden commented on packages/theme/modules/catalog/category/components/breadcrumbs/CategoryBreadcrumbs.vue
> +      return (categoryTree === null
Return early?

2022-04-06 15:23 UTC, sethidden commented on packages/theme/modules/catalog/category/components/breadcrumbs/CategoryBreadcrumbs.vue
> +      // TODO do not hardcode 'default' as this store URL can change, add some stripStore helper
Fixed in breadcrumbs, still need to add in Sidebar

2022-04-06 15:23 UTC, sethidden commented on packages/theme/modules/catalog/category/components/breadcrumbs/CategoryBreadcrumbs.vue
> +      return (categoryTree === null
done

2022-04-07 07:08 UTC, sethidden commented on packages/theme/modules/catalog/category/components/sidebar/CategorySidebar.vue
> +    } = useCategoryLogic();
Extracted the logic from CategorySidebar.vue, MobileCategorySidebar.vue and CategoryBreadcrumbs.vue regarding detection of active category in the category tree.

Now it's all in one composition function. Notice how many things were removed in this file because of this

2022-04-07 07:11 UTC, sethidden commented on packages/theme/modules/catalog/pages/default.vue
> +          <CategoryBreadcrumbs class="breadcrumbs" />
Can now use the new useCategoryLogic in default.vue and plug in the props to here

2022-04-07 07:16 UTC, sethidden commented on packages/theme/modules/catalog/category/helpers/index.ts
> +export const useCategoryLogic = () => {
I though of maybe keeping this new composable's logic inside the category store instead. Then I realized the store should keep only data — not bolted-on logic like computed properties which query the current route etc.

2022-04-07 07:17 UTC, sethidden commented on packages/theme/modules/catalog/category/helpers/index.ts
> +  // on localhost the default store is localhost:3000/default/ but in a multi-store instance this can change
```suggestion
  // on localhost the default store is localhost:3000/default/ but in a multi-store Magento instance this can change
```

2022-04-08 07:34 UTC, Frodigo commented
@sethidden when I go to `/c/gear/bags.html` category and click on "gear" in breadcrumbs, vsf redirects me to 404 page because there is a wrong URL: `gear.html` but should be `c/gear.html`
![Screenshot 2022-04-08 at 09 34 12](https://user-images.githubusercontent.com/11998249/162386995-386e9d4f-7f51-47d1-b90b-cd1403ad1185.png)

2022-04-08 07:35 UTC, sethidden commented
Hmm I was fixing that, maybe I didn't push that out. Thanks, I'll take a look

2022-04-08 07:36 UTC, Frodigo commented
It's possible to move breadcrumbs from the products section to place between the header and topbar? It will be more consistent with other places like product pages.

2022-04-08 07:46 UTC, Frodigo requested changes

2022-04-08 07:46 UTC, Frodigo commented on packages/theme/modules/catalog/category/components/breadcrumbs/CategoryBreadcrumbs.vue
> +      link: `/${currentMagentoStoreName}/c${ancestor.slug}`,
It would be better to use `localePath` helper from i18n to build URL. Something like this: `${app.localePath('/c${ancestor.slug})}`.

then `currentMagentoStoreName` is no longer needed.

2022-04-08 07:46 UTC, Frodigo commented on packages/theme/modules/catalog/category/components/sidebar/CategorySidebar.vue
```suggestion
```

2022-04-08 07:46 UTC, Frodigo commented on packages/theme/modules/catalog/category/components/sidebar/CategorySidebar.vue
> +    } = useCategoryLogic();
Please align about that with @bartoszherba. He lastly told me that he is doing something familiar, but using provide/inject.

2022-04-08 07:46 UTC, Frodigo commented on packages/theme/modules/catalog/category/components/sidebar/MobileCategorySidebar/MobileCategorySidebar.vue
>        current: currentCategory, history, currentItems, onGoCategoryUp, onGoCategoryDown,
There is the sling error in next line: `ESLint: Unsafe argument of type `any` assigned to a parameter of type `CategoryTreeInterface[]`.(@typescript-eslint/no-unsafe-argument)`

2022-04-08 08:57 UTC, sethidden commented on packages/theme/modules/catalog/category/components/sidebar/MobileCategorySidebar/MobileCategorySidebar.vue
>        current: currentCategory, history, currentItems, onGoCategoryUp, onGoCategoryDown,
![image](https://user-images.githubusercontent.com/5359825/162402015-659f894b-600f-486f-84c1-bd7f01cbe212.png)
It doesn't appear to me (left space error intentionally)

2022-04-08 09:01 UTC, sethidden commented on packages/theme/modules/catalog/category/components/sidebar/CategorySidebar.vue
I think GitHub is rendering something weird here - what do you mean?

2022-04-08 09:07 UTC, sethidden commented on packages/theme/modules/catalog/category/components/sidebar/MobileCategorySidebar/MobileCategorySidebar.vue
>        current: currentCategory, history, currentItems, onGoCategoryUp, onGoCategoryDown,
About provide/inject - Bart said he's doing something different than I'm doing here

2022-04-08 09:12 UTC, Frodigo commented on packages/theme/modules/catalog/category/components/sidebar/CategorySidebar.vue
just removing empty line, but nevermind :)

2022-04-08 09:12 UTC, Frodigo commented on packages/theme/modules/catalog/category/components/sidebar/MobileCategorySidebar/MobileCategorySidebar.vue
>        current: currentCategory, history, currentItems, onGoCategoryUp, onGoCategoryDown,
ok, thanks

2022-04-08 09:15 UTC, Frodigo requested changes
Looks good, some small adjustments and we are ready to go!

2022-04-08 09:15 UTC, Frodigo commented on packages/theme/modules/catalog/category/components/breadcrumbs/CategoryBreadcrumbs.vue
> +    const context = useContext();
```suggestion
    const { app }  = useContext();
```

2022-04-08 09:15 UTC, Frodigo commented on packages/theme/modules/catalog/category/components/breadcrumbs/CategoryBreadcrumbs.vue
> +      link: context.app.localePath(`/c${slug}`),
```suggestion
      link: app.localePath(`/c${slug}`),
```

2022-04-08 09:18 UTC, Frodigo approved these changes

2022-04-08 09:23 UTC, merged