docs: add useCart JSDoc documentation
vuestorefront/magento2 pull request #827
Opened 2022-04-07 22:21 UTC by roziscoding

- chore: add gitflow actions (#379)
- docs: added roadmap to the docs (#380)
- fix(theme): refactor and fix store switcher (#383)
- fix(theme): fix preselection sort order when query param is available (#385)
- fix: broken cart after placing order as guest (#386)
- fix(theme): fix flashing category page (#387)
- fix(theme): fix flashing category page (#388)
- fix: default billing information does not appear on address (#382)
- chore: upgraded vsf core to 2.5.4 (#389)
- fix(composables): update url resolver clearing patter to remove locale prefix (#390)
- fix(theme): fix links to catch current locale (#391)
- style(theme): aligned titles in my account menu (#400)
- feat(middleware): added i18n route middleware (#408)
- fix(theme): update localisation for all :link bindings (#416)
- docs(theme): update custom queries documentation to be more friendly and explicit (#418)
- chore(theme): removed html-validator (#414)
- refactor: update dependencies (#420)
- refactor(theme): enables currency switcher on TopBar.vue (#421)
- fix(theme): fix 404 issue when redirecting to address details page (#424)
- test: scaffold unit tests in composables and api client package (#419)
- fix(theme): fix disappearing category sidebar filter change (#423)
- fix(theme): out of stock product will no longer break cart (#404)
- Revert "refactor(theme): enables currency switcher on TopBar.vue (#421)" (#426)
- refactor(i18n): changed i18n middleware to plugin and fix store switc… (#425)
- refactor(theme): changed i18n midl. to plugin & fix store switcher by url (#431)
- fix(api-client): update default mutation error handling for apollo client (#429)
- fix: expired user token (#392)
- refactor(theme): enable the currency switcher on `TopBar.vue` (#430)
- fix(theme): remove redundant cart load actions (#438)
- perf(theme): updated nuxt.config.js to improve rebuild performance during development (#443)
- fix(theme): update localisation for all :link bindings (#450)
- fix: handle currency switch issue (#441)
- chore: align main with develop (#455)
- fix(minicart): fix resolving configurable variants data (#456)
- feat: added translations for german store (#459)
- fix(composable): fix clearing cart on customer logout (#458)
- fix(theme): fix fcPlugin issuse when cookies were not set yet - added default currency fallback (#460)
- fix(api-client): update all cart related queries/mutation to include configurable variants data (#461)
- fix(theme): fix adding product to a wishlist from a listed category page (#464)
- fix(theme): add debounced update quantity action so it will be possible to insert multidigital value (#465)
- fix(theme): fix customer account update data and password change functionality (#469)
- perf(general): add performance improvement changes (#471)
- Revert "perf(general): add performance improvement changes (#471)" (#472)
- fix: loosing data when moving between steps on the checkout (#440)
- fix(composables): re-calculate cart when changing shipping-method (#473)
- feat(theme): add missing german translations (#479)
- feat: added nuxt-img and possibility to use external image providers (#467)
- fix(theme): fix mobile home button alignment (#475)
- refactor: m2-69. ssr optimization for default layout (#477)
- fix: incorrect shipping method price displayed in order summary (#481)
- fix(theme): fix footer lazy hydration (#488)
- fix(theme): fixed product layout tablet (#487)
- fix(theme): added spacing on the left and right of the checkout page (#486)
- fix(theme): fixed payment setup style discrepancies (#484)
- fix: incorrect shipping method price displayed in order summary (#496)
- fix(theme): fixed cms page loading (#495)
- fix(theme): fixed review page is empty if there are no reviews (#485)
- fix(theme): ssr optimization for default layout (#506)
- fix(theme): orders history table - no order details button on mobile (#505)
- fix(theme): product bundle visual issue (#504)
- fix(theme): add wishlist loading when customer is logging in (#509)
- fix(theme): fix setting proper store and locale if there is no cookie (#508)
- feat(recaptcha): add recaptcha (#401)
- chore: added sentry (#507)
- feat: added support for @vue-storefront/cache module (#482)
- fix: billing address overwrites shipping address when copy flag is set (#510)
- build: added npm registry to dockerfile (#511)
- build(deployment): added reCahptcha env variables, and modified deploy action (#515)
- build(theme): extracted styles to separate .css chunks (#516)
- fix(theme, composable): expired user token issue (#519)
- fix(theme): update login modal to handle translations (#521)
- chore(theme): removed redis, sentry and reCaptcha config from nuxt.config.js (#522)
- fix: added missing translations (#525)
- fix: disable ATC button while new product configuration is being loaded (#523)
- chore: added possibility to extend nuxt.config during deployment (#524)
- chore: disabled rechaptcha by default (#531)
- fix(theme): add html unescaping in HTMLContent component (#532)
- fix(theme): use translation function in all occurance of error[0] in theme (#529)
- build: removed recaptcha from deployment config (#534)
- build: fixed recaptcha env variable binding (#537)
- fix(composable): update useFacets to work with a customQueries (#536)
- fix: configurable product should work when only one attribute is used (#540)
- refactor(theme): performance improvements (#541)
- fix(theme): fix missing address details tab for non-english locale stores (#542)
- chore(theme): added missing translations (#553)
- fix: the ability to close quick search using the keyboard (#552)
- fix(theme): update address action will now properly load address data in form (#551)
- fix(theme): fix add to wishlist button on catgory listing view for a mobile devices (#554)
- fix(theme): save or update of address details in the customer account will no longer yield 404 (#555)
- chore: updated dependencies & configuration management (#538)
- fix: fixed InstagramFeed component (#557)
- fix: changed header spacing (#556)
- build: add enterprise deployment (#561)
- chore: allign main to develop after 1.0.0-rc.5.4 release (#560)
- refactor: added loazy loaded components for default layout and app header (#564)
- refactor(theme): updated deployment & dependencies (#563)
- refactor(theme): added lazy loading for offscreen images on homepage (#565)
- fix(theme): fix missing shipping address form on the checkout for a comming back customer (#566)
- refactor(theme): remove core _theme module (#567)
- fix(theme): fix dompurify arguments injection (#573)
- feat: mobile menu (#569)
- chore: fixed some error reported by eslint (#562)
- fix: small fixes for mobile (#580)
- build(dockerfile): binded MAGENTO_BASE_URL to the env variable (#597)
- fix(build): changed image provider to ipx (#599)
- refactor(general): refactor how and where the cart is loaded - add loadTotalQuantity method on the cart composable as sometimes this is the only information needed - add lazy load for a minicart - header will pull only total quantity data instead of loading whole cart
- feat(theme): add conditional rendering for a store switcher and currency switcher
- build(tsconfig): changed target in tdconfig files from es5 to es2019
- build(github actions): updated draft release and merge release GH actions
- refactor(theme): moved loadStores and loadCurrencies  to separate components
- refactor(theme): refactored store switcher
- refactor(theme): refactored currency swithcer
- feat(theme): added useApi composable, refactored topBar
- chore(composables): made useCustomQuery composables deprecated
- feat(theme): - add wishlist lazyload and totalItems shared field
- perf(theme): lazy load loginModal
- feat(theme): add LoadWhenVisible component and lazyload footer
- refactor(theme): changed VSF logo and favicon
- refactor(theme): fixed cms pages layout
- build: added redis
- build: fixed redis cache invalidation
- build(build): fixed merge-release GH action
- fix(theme): clear login modal reset [...]

2022-04-13 04:42 UTC, Frodigo requested changes

2022-04-13 04:42 UTC, Frodigo commented on packages/api-client/src/api/addVirtualProductsToCart/index.ts
> +import { Context } from '../../types/context';
```suggestion
import type { Context } from '../../types/context';
```

2022-04-13 04:42 UTC, Frodigo commented on packages/api-client/src/api/addConfigurableProductsToCart/index.ts
> +import { Context } from '../../types/context';
```suggestion
import type { Context } from '../../types/context';
```

2022-04-13 04:42 UTC, Frodigo commented on packages/api-client/src/api/addDownloadableProductsToCart/index.ts
> +import { Context } from '../../types/context';
```suggestion
import type { Context } from '../../types/context';
```

2022-04-13 04:42 UTC, Frodigo commented on packages/api-client/src/api/applyCouponToCart/index.ts
> +import { Context } from '../../types/context';
```suggestion
import type { Context } from '../../types/context';
```

2022-04-13 04:42 UTC, Frodigo commented on packages/api-client/src/api/cart/index.ts
> +import { CartQuery, CartQueryVariables } from '../../types/GraphQL';
```suggestion
import type { CartQuery, CartQueryVariables } from '../../types/GraphQL';
```

2022-04-13 04:42 UTC, Frodigo commented on packages/api-client/src/api/customerCart/index.ts
>  import { CustomQuery } from '@vue-storefront/core';
```suggestion
import type { CustomQuery } from '@vue-storefront/core';
```

2022-04-13 04:42 UTC, Frodigo commented on packages/api-client/src/api/customerCart/index.ts
> +import { CustomerCartQuery } from '../../types/GraphQL';
```suggestion
import type { CustomerCartQuery } from '../../types/GraphQL';
```

2022-04-13 04:42 UTC, Frodigo commented on packages/api-client/src/api/customerCart/index.ts
>  import { Context } from '../../types/context';
```suggestion
import type { Context } from '../../types/context';
```

2022-04-13 04:42 UTC, Frodigo commented on packages/api-client/src/api/removeCouponFromCart/index.ts
> +import { Context } from '../../types/context';
```suggestion
import type { Context } from '../../types/context';
```

2022-04-13 04:42 UTC, Frodigo commented on packages/api-client/src/api/removeItemFromCart/index.ts
>  import { CustomQuery } from '@vue-storefront/core';
```suggestion
import type { CustomQuery } from '@vue-storefront/core';
```

2022-04-13 04:42 UTC, Frodigo commented on packages/api-client/src/api/removeItemFromCart/index.ts
> +import { Context } from '../../types/context';
```suggestion
import type { Context } from '../../types/context';
```

2022-04-13 04:42 UTC, Frodigo commented on packages/api-client/src/api/updateCartItems/index.ts
>  import { CustomQuery } from '@vue-storefront/core';
```suggestion
import type { CustomQuery } from '@vue-storefront/core';
```

2022-04-13 04:42 UTC, Frodigo commented on packages/api-client/src/api/updateCartItems/index.ts
> +import { Context } from '../../types/context';
```suggestion
import type { Context } from '../../types/context';
```

2022-04-13 04:43 UTC, Frodigo commented on docs/.vuepress/config.js
> +        ],
I can't see new documented API methods here. Could you add them?

2022-04-13 18:25 UTC, roziscoding commented on docs/.vuepress/config.js
> +        ],
Done :)

2022-04-14 06:02 UTC, Frodigo approved these changes

2022-04-14 06:08 UTC, merged