feat!: make `error` and `loading` properties readonly on `useMakeOrder` composable
vuestorefront/magento2 pull request #878
Opened 2022-04-18 05:51 UTC by VitorLuizC

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-04-18 06:04 UTC, VitorLuizC commented on packages/theme/composables/useMakeOrder/commands/placeOrderCommand.ts
> +    return data.placeOrder;
I found a way to type the `context`, but TS started to complain when I did. First, because `$vsf` doesn't exist in `context` but in `context.app`; and then because `data.placeOrder.order` is of type `Order` instead of `PlaceOrderOutput` which is its parent (`data.placeOrder`).

It looks like I fixed an error in `placeOrderCommand`, but I would appreciate it if you guys review this part with care.

2022-04-19 07:08 UTC, sethidden commented on packages/theme/composables/useMakeOrder/commands/placeOrderCommand.ts
> +    return data.placeOrder;
You can also just use import { Context } from '@nuxt/types' since that's the underyling type of ReturnType<useContext>

2022-04-20 06:17 UTC, sethidden commented on packages/theme/composables/useMakeOrder/commands/placeOrderCommand.ts
> +  execute: async (app: NuxtAppOptions, cartId: string): Promise<PlaceOrderOutput | null> => {
```suggestion
  execute: async (context: Context, cartId: string): Promise<PlaceOrderOutput | null> => {
```

All our other *Command.ts files use context as the arg here, so even if the @nuxt/types Context doesn't work, the not-so-beautiful Return<useContext> type is better than changing the convention

2022-04-20 06:18 UTC, sethidden commented on packages/theme/composables/useMakeOrder/commands/placeOrderCommand.ts
> +    return data.placeOrder;
Followed up in https://github.com/vuestorefront/magento2/pull/878#discussion_r853762397

2022-04-20 07:06 UTC, Frodigo requested changes

2022-04-20 07:06 UTC, Frodigo commented on packages/theme/composables/useMakeOrder/index.ts
> +      placedOrder = await placeOrderCommand.execute(app, cart.value.id);
Context must be pass here, not app.

2022-04-21 06:46 UTC, Frodigo approved these changes

2022-04-21 06:47 UTC, merged