feat!: make `error` and `loading` properties readonly on `useNewsletter` composable
vuestorefront/magento2 pull request #879
Opened 2022-04-18 08:56 UTC by VitorLuizC

## Description
- **[BREAKING CHANGE]** Make the `error` and `loading` properties readonly (they're refs);
- **[BREAKING CHANGE]** Remove `SubscriptionStatusesEnum` object from `useNewsletter` as it was already declared in `~/modules/GraphQL/types`.
- Create `UseNewsletterInterface` similar as other composables;
- Add type for the params object received by `UseNewsletterInterface.updateSubscription` method;
- Write TSDocs for `subscribeEmailToNewsletter` API method and its GraphQL query;
- Write TSDocs for `useNewsletter` composable and its types;
- Convert `useNewsletter`, `subscribeEmailToNewsletter` and other root-level functions into function declarations (since it's better for the docs generator);
- Export `useNewsletter` types in `~/composables`;

## Related Issue
https://vsf.atlassian.net/browse/M2-388

## Motivation and Context
Improves the DX of the `useNewsletter` composable.

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-04-19 06:59 UTC, bartoszherba requested changes

2022-04-19 06:59 UTC, bartoszherba commented on packages/api-client/src/api/subscribeEmailToNewsletter/index.ts
> +import { SubscribeEmailToNewsletterMutation, SubscribeEmailToNewsletterMutationVariables } from '../../types/GraphQL';
```suggestion
import type { SubscribeEmailToNewsletterMutation, SubscribeEmailToNewsletterMutationVariables } from '../../types/GraphQL';
```

2022-04-19 15:35 UTC, VitorLuizC commented
@bartoszherba I've added types for `updateSubscriptionCommand` and used the same strategy as #878, which receives `app` instead of `context` in the command `execute` method.

2022-04-20 07:09 UTC, Frodigo commented
> @bartoszherba I've added types for `updateSubscriptionCommand` and used the same strategy as #878, which receives `app` instead of `context` in the command `execute` method.

@bartoszherba @VitorLuizC why do we change params in commands from context to app?

2022-04-21 06:47 UTC, Frodigo submitted a review, later dismissed

2022-04-21 06:53 UTC, Frodigo approved these changes

2022-04-21 09:12 UTC, bartoszherba approved these changes

2022-04-21 10:01 UTC, Frodigo approved these changes

2022-04-21 11:52 UTC, merged