feat!: make `error` and `loading` properties readonly on `usePaymentProvider` composable
vuestorefront/magento2 pull request #881
Opened 2022-04-18 19:26 UTC by VitorLuizC

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-04-19 05:39 UTC, sethidden approved these changes

2022-04-19 06:56 UTC, bartoszherba requested changes

2022-04-19 06:56 UTC, bartoszherba commented on packages/api-client/src/api/getAvailablePaymentMethods/index.ts
> +import { GuestAvailablePaymentMethodsQuery, GuestAvailablePaymentMethodsQueryVariables } from '../../types/GraphQL';
```suggestion
import type { GuestAvailablePaymentMethodsQuery, GuestAvailablePaymentMethodsQueryVariables } from '../../types/GraphQL';
```

2022-04-19 06:56 UTC, bartoszherba commented on packages/api-client/src/api/getAvailablePaymentMethods/index.ts
> +  const { paymentMethods } = context.extendQuery(customQuery, {
What rules do you use to format code?

2022-04-19 06:56 UTC, bartoszherba commented on packages/api-client/src/api/setPaymentMethodOnCart/index.ts
> +import { SetPaymentMethodOnCartInput, SetPaymentMethodOnCartMutation, SetPaymentMethodOnCartMutationVariables } from '../../types/GraphQL';
```suggestion
import type { SetPaymentMethodOnCartInput, SetPaymentMethodOnCartMutation, SetPaymentMethodOnCartMutationVariables } from '../../types/GraphQL';
```

2022-04-19 06:56 UTC, bartoszherba commented on packages/theme/composables/usePaymentProvider/commands/setPaymentMethodOnCartCommand.ts
> +    return data.setPaymentMethodOnCart.cart.available_payment_methods ?? [];
```suggestion
    return data?.setPaymentMethodOnCart?.cart?.available_payment_methods ?? [];
```

2022-04-19 15:37 UTC, VitorLuizC commented on packages/api-client/src/api/getAvailablePaymentMethods/index.ts
> +  const { paymentMethods } = context.extendQuery(customQuery, {
Just executed Prettier and ESLint autofix in sequence. I'm using VSCode extensions for both, so these are my Ctrl + F.

2022-04-21 09:12 UTC, bartoszherba approved these changes

2022-04-21 09:58 UTC, merged