refactor:
vuestorefront/magento2 pull request #884
Opened 2022-04-19 11:16 UTC by bartoszherba

## Description
- move desktop category filters from SfSidebar to the main layout column

## Motivation and Context
UX improvement

## Screenshots (if appropriate):
![Uploading Screenshot 2022-04-19 at 13.15.53.png…]()

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-04-19 13:21 UTC, sethidden reviewed
Just a quick code-only review, didn't checkout

2022-04-19 13:21 UTC, sethidden commented on packages/theme/modules/catalog/category/components/filters/CategoryFilters.vue
> +      title="Filters"
```suggestion
      :title="$t('Filters')"
```

2022-04-19 13:21 UTC, sethidden commented on packages/theme/modules/catalog/category/components/filters/CategoryFilters.vue
> +      }
```suggestion
window?.scroll(0, 0)
```

2022-04-20 06:29 UTC, Frodigo requested changes
Looks good! I left small comments.

Thanks @bartoszherba

2022-04-20 06:29 UTC, Frodigo commented on packages/theme/modules/catalog/category/components/filters/CategoryFilters.vue
> +            {{ $t('Done') }}
Can you change 'Done' to 'Apply filters'?

2022-04-20 06:29 UTC, Frodigo commented on packages/theme/modules/catalog/category/components/filters/CategoryFilters.vue
> +window?.scroll(0, 0)
Consider using this one: https://nuxtjs.org/docs/components-glossary/scrolltotop/ instead of a window.scroll. 

Besides, please fix the indentation issue.

2022-04-20 06:29 UTC, Frodigo commented on packages/theme/modules/catalog/category/components/filters/FiltersSidebar/SelectedFilters.vue
> +      <a
Please use `button` here instead of `a`.

2022-04-20 06:29 UTC, Frodigo commented on packages/theme/modules/catalog/pages/category.vue
> +  @include for-mobile {
Please add an empty line, between each CSS rule.

2022-04-20 07:51 UTC, bartoszherba commented on packages/theme/modules/catalog/category/components/filters/CategoryFilters.vue
> +window?.scroll(0, 0)
No, this is not a child root. And we are not rerendering with the usage of the router.

2022-04-20 10:37 UTC, Frodigo requested changes
@bartoszherba I added one suggestion, moreover, can you also change the button "done" to "apply filters" on the desktop? Looks like your change works only on mobile devices.

2022-04-20 10:37 UTC, Frodigo commented on packages/theme/modules/catalog/category/components/filters/useFilters.ts
> +  const getRemovableFilters = (filters: Aggregation[], selected: SelectedFiltersInterface) => {
Consider make this in more declarative way:

```javascript
const getRemovableFilters = (filters: Aggregation[], selected: SelectedFiltersInterface) => {
    const result = [];

    filters.forEach((filter) => {
      filter.options
        .filter((option) => (selected[filter.attribute_code] ?? []).includes(option.value))
        .forEach((option) => {
          result.push({
            id: filter.attribute_code, name: filter.label, label: option.label, value: option.value,
          });
        });
    });

    return result;
  };
```

2022-04-20 10:45 UTC, bartoszherba commented on packages/theme/modules/catalog/category/components/filters/useFilters.ts
> +  const getRemovableFilters = (filters: Aggregation[], selected: SelectedFiltersInterface) => {
I don't understand

2022-04-20 10:52 UTC, Frodigo commented on packages/theme/modules/catalog/category/components/filters/useFilters.ts
> +  const getRemovableFilters = (filters: Aggregation[], selected: SelectedFiltersInterface) => {
Maybe this can help you understand: https://medium.com/weekly-webtips/imperative-vs-declarative-programming-in-javascript-25511b90cdb7 Please check "Imperative versus declarative cycles and arrays".


So my comment was about replacing if in the forEach (imperative approach) with the `filter` method (declarative approach).

2022-04-20 12:46 UTC, bartoszherba commented on packages/theme/modules/catalog/category/components/filters/useFilters.ts
> +  const getRemovableFilters = (filters: Aggregation[], selected: SelectedFiltersInterface) => {
The actual result is a mix of options and filers data so it involves a nested loop and mapping of two objects into one, the case is not as simple as in your example and, because it was already accepted and I do not see any benefit from that change, just troubles I will leave it as it is.

2022-04-20 15:33 UTC, Frodigo approved these changes

2022-04-20 15:33 UTC, merged