feat: header categories
vuestorefront/magento2 pull request #903
Opened 2022-04-21 12:06 UTC by bartoszherba

## Description
- add multilevel categories navigation

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):
![Screenshot 2022-04-21 at 14 06 13](https://user-images.githubusercontent.com/16045377/164454599-0b301c6e-ba56-46da-bf2b-96666238835d.png)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-04-26 06:09 UTC, sethidden commented on .eslintrc.js
> +    "jest/expect-expect": "off"
```suggestion
```

You can't skip using "expect", even if getByRole returns an error

2022-04-26 06:09 UTC, sethidden commented on .eslintrc.js
> +    "jest/expect-expect": "off"
```suggestion
```

You can't skip using "expect", even if getByRole returns an error

2022-04-26 06:10 UTC, sethidden commented on packages/theme/components/Header/Navigation/__tests__/HeaderNavigation.spec.js
> +    getByRole('link', { name: /women/i });
```suggestion
    expect(getByRole('link', { name: /women/i })).toBeTruthy();
```

2022-04-26 06:10 UTC, sethidden commented on packages/theme/components/Header/Navigation/__tests__/HeaderNavigation.spec.js
> +    getByRole('link', { name: /women/i });
```suggestion
    expect(getByRole('link', { name: /women/i })).toBeTruthy();
```

2022-04-26 06:11 UTC, sethidden commented on packages/theme/components/Header/Navigation/__tests__/HeaderNavigation.spec.js
> +    getByRole('link', { name: /women/i });
(repeat for all the getByRoles below)

2022-04-26 06:11 UTC, sethidden commented on packages/theme/components/Header/Navigation/__tests__/HeaderNavigation.spec.js
> +    getByRole('link', { name: /women/i });
(repeat for all the getByRoles below)

2022-04-26 06:22 UTC, sethidden reviewed
Left some comments. Will leave some more in a second aswell because I'm scared this'll get merged while I'm reviewing again

2022-04-26 06:22 UTC, sethidden requested changes
(meant to request changes)

2022-04-26 06:24 UTC, sethidden commented on packages/theme/components/Header/Navigation/__tests__/HeaderNavigationSubcategories.spec.js
> +    expect(queryByTestId(/navigation-subcategories/i)).toBeNull();
```suggestion
    expect(queryByTestId('navigation-subcategories')).toBeNull();
```
As far as I've seen in the code you use `data-testid='navigation-subcategories'` not `:data-testid="'navigation-subcategories' + somePrefix"`, so the regex is not necessary

2022-04-26 06:25 UTC, sethidden commented on packages/theme/components/Header/Navigation/__tests__/HeaderNavigationSubcategories.spec.js
> +    getByRole('link', { name: /bottoms/i });
```suggestion
    expect(getByRole('link', { name: /tops/i })).toBeTruthy();
    expect(getByRole('link', { name: /bottoms/i })).toBeTruthy();
```

2022-04-26 06:49 UTC, sethidden commented on packages/theme/components/Header/Navigation/__tests__/HeaderNavigation.spec.js
> +useUiHelpers.mockReturnValue(useUiHelpersMock());
I assume you did this because otheriwse a `route.value` error appears when jest imports useUihelpers

You can initialize route.value like
```ts
const sharedOptions = { props: { categoryTree: CategoryTreeDataMock[0].children }, routes: [{ path: '/' }]}
const initialCall = (vue, router, _store) => {
  router.push('/');
};
```

then in the test

```
  it('displays main categories', () => {
    const { getByRole } = render(HeaderNavigation, sharedOptions, initialCall); // <-- initialCall added
    expect(getByRole('link', { name: /women/i })).toBeTruthy();
    expect(getByRole('link', { name: /gear/i })).toBeTruthy();
    expect(getByRole('link', { name: /training/i })).toBeTruthy();
  });
```

Jest - after the above changes - will render nuxt-links instead of `a role="link"`, which is good because the new categories are also nuxt-links in the app (not `<a href=""` like they are with the current assertions) 
<img width="442" alt="image" src="https://user-images.githubusercontent.com/5359825/165238147-2eccf277-6346-4154-875c-c86d093c3a5b.png">

2022-04-26 06:55 UTC, sethidden commented on packages/theme/components/Header/Navigation/__tests__/HeaderNavigation.spec.js
> +useUiHelpers.mockReturnValue(useUiHelpersMock());
In the state I've shown above it's impossible to access the nuxt-img, so I guess it's best to add a `data-testid="link"` to HeaderNavigation.vue on the SfLink component

2022-04-26 06:56 UTC, sethidden commented on packages/theme/components/Header/Navigation/__tests__/HeaderNavigation.spec.js
> +useUiHelpers.mockReturnValue(useUiHelpersMock());
The point of all of this is to test as much real code as possible, hence why I'm bothering you with the mocking of useUiState that much

2022-04-26 06:56 UTC, sethidden commented on packages/theme/components/Header/Navigation/__tests__/HeaderNavigationSubcategories.spec.js
> +useUiHelpers.mockReturnValue(useUiHelpersMock());
```suggestion
```

(same as in previous comment)

2022-04-26 06:59 UTC, sethidden commented on packages/theme/components/Header/Navigation/HeaderNavigation.vue
> +    const hasChildren = (category: CategoryTree) => Boolean(category?.children);
```suggestion
    const hasChildren = computed(() => Boolean(currentCategory?.children);
```
That way you can avoid calling the function in the template

2022-04-26 07:00 UTC, sethidden commented on packages/theme/components/Header/Navigation/HeaderNavigationSubcategories.vue
> +    const hasChildren = (category: CategoryTree) => Boolean(category?.children.length > 0);
You have the same function in HeaderNavigation.vue, just without the `.length`

2022-04-26 07:09 UTC, bartoszherba commented on .eslintrc.js
> +    "jest/expect-expect": "off"
I just did and can, what is the problem? We discussed that on slack.

2022-04-26 07:10 UTC, Frodigo commented on packages/theme/components/Header/Navigation/__tests__/HeaderNavigation.spec.js
> +    getByRole('link', { name: /women/i });
I don't agree with that.  getByRole is implicitly an assertion so it's redundant to wrap it by the expected

2022-04-26 07:11 UTC, bartoszherba commented on packages/theme/components/Header/Navigation/__tests__/HeaderNavigation.spec.js
> +useUiHelpers.mockReturnValue(useUiHelpersMock());
No, I want to mock everything but class under test. This is how unit tests work.

2022-04-26 07:13 UTC, bartoszherba commented on packages/theme/components/Header/Navigation/__tests__/HeaderNavigation.spec.js
> +useUiHelpers.mockReturnValue(useUiHelpersMock());
The point of UT is to test ONLY the class under tests, not as much code as possible - i want to test ONLY the code under test in a controlled environment.

2022-04-26 07:13 UTC, bartoszherba commented on packages/theme/components/Header/Navigation/__tests__/HeaderNavigationSubcategories.spec.js
> +useUiHelpers.mockReturnValue(useUiHelpersMock());
Nope, mock everything but class under test.

2022-04-26 07:14 UTC, bartoszherba commented on packages/theme/components/Header/Navigation/HeaderNavigationSubcategories.vue
> +    const hasChildren = (category: CategoryTree) => Boolean(category?.children.length > 0);
I do not want create separate file just to have this function.

2022-04-26 07:17 UTC, sethidden commented on .eslintrc.js
> +    "jest/expect-expect": "off"
Ah I see in the vue testing library docs that they use it that way aswell, ie getBy* is the same as expect(). Then it'd make sense to register the assertions you use as assert fns with the rule
```
{
  "jest/expect-expect": [
    "error",
    {
      "assertFunctionNames": ["expect", "getByText", ...etc],
      "additionalTestBlockFunctions": []
    }
  ]
}
```

2022-04-26 08:55 UTC, bartoszherba commented on packages/theme/components/Header/Navigation/__tests__/HeaderNavigationSubcategories.spec.js
> +    expect(queryByTestId(/navigation-subcategories/i)).toBeNull();
Ok, fixed.

2022-04-26 08:56 UTC, bartoszherba commented on packages/theme/components/Header/Navigation/HeaderNavigation.vue
> +    const hasChildren = (category: CategoryTree) => Boolean(category?.children);
I think that pure function will be ultimately faster.

2022-04-26 09:36 UTC, Frodigo approved these changes

2022-04-26 09:45 UTC, sethidden commented
Reported one more issue to Bartek on Slack - GitHub doesn't like .mov files for some reason

2022-04-26 09:45 UTC, sethidden requested changes
(see above)

2022-04-27 06:37 UTC, sethidden submitted a review, later dismissed
(blocking pr for now because I'll be testing this with a screen reader. I'll unblock once I'm done)

2022-04-27 06:55 UTC, sethidden commented on packages/theme/components/Header/Navigation/HeaderNavigationSubcategories.vue
> +          />
```suggestion
  <div class="sf-title sf-title--level-5" <!-- the classes aren't actually named like that, just a demo -->
```

Visually setting a heading level 5 makes sense. Semantically though, there's no heading level 4 above this heading level 5, so the heading structure is disorganized.

It's fine to use just a dumb div with a class to keep the visual feel of heading level 5 but leave out the (inaccurate) semantics. It'd be best to have a correct heading structure instead of the div, but the div is fine for now.

VoiceOver reads "heading level 5, link" when hovering this element, but doesn't read heading levels for the top-level categories "Men", "Women" etc.

2022-04-27 07:01 UTC, sethidden commented on packages/theme/components/Header/Navigation/HeaderNavigationSubcategories.vue
> +              tabindex="-1"
So I understand this disables the tab navigation because there's arrow navigation.
This worries me because:
- on one hand, there's keyboard navigation in the form of keyboard arrows so this should theoretically be fine
- on the other hand, the user will not know that such navigation exists. You can expect the user to know the built-in browser navigation stuff (Tab, Shift-Tab) but downright disabling Tab navigation is a big deal

I'm pretty sure you won't want to rework the entire kbd navigation to support tab, so I'm writing this as a heads up

2022-04-27 07:09 UTC, sethidden commented on packages/theme/components/Header/Navigation/HeaderNavigationSubcategories.vue
> +    },
```suggestion
```
Is there any way to avoid this? The component could render HTML, but the focus information is contained in the browser. 

Something with https://developer.mozilla.org/en-US/docs/Web/API/Document/activeElement maybe? ie. if document.activeElement === (this component's ref) then setupNav

2022-04-27 07:14 UTC, bartoszherba commented on packages/theme/components/Header/Navigation/HeaderNavigationSubcategories.vue
> +    },
this is a visibility flag

2022-04-27 07:17 UTC, sethidden commented on packages/theme/components/Header/Navigation/HeaderNavigation.vue
> +        tabindex="0"
This applies to the HeaderNavigationItem's root element, which is a div. Divs are not interactive (foucsable with tab) elements by default, unlike the `<a>` (hopefully SfLink's root element) which is interactive by default. Would it be possible to make HeaderNavigationItem have a root element in the form of `<a>` so the tabindex is not needed?

HeaderNavigationSubcategories work fine (focus the link directly)

2022-04-27 07:18 UTC, sethidden commented on packages/theme/components/Header/Navigation/HeaderNavigation.vue
> +        tabindex="0"
Very ugly but potentially useful - it's possible to access refs of refs, so you could do this.$refs.myRef.$refs.link.focus()

https://stackoverflow.com/a/58358598/10706046

2022-04-27 07:33 UTC, sethidden reviewed
unblocking

2022-04-27 12:38 UTC, Frodigo approved these changes
Looks good. for now. Comments reported by @sethidden  will be addressed by other PRs.

2022-04-28 06:15 UTC, bartoszherba commented on packages/theme/components/Header/Navigation/HeaderNavigation.vue
> +        tabindex="0"
Thanks but we are using composition API so `this.whatever` will not work.

2022-04-28 06:29 UTC, bartoszherba commented on packages/theme/components/Header/Navigation/HeaderNavigationSubcategories.vue
> +          />
Changed that to h2

2022-04-28 06:30 UTC, bartoszherba commented on packages/theme/components/Header/Navigation/HeaderNavigation.vue
> +        tabindex="0"
, Root will be now <a> instead of <div>, tabindex not only indicate that something can be tabbed but also tab order so i leave it as it is, just updated the value 0 > 1

2022-04-28 07:52 UTC, sethidden commented on packages/theme/components/Header/Navigation/HeaderNavigationSubcategories.vue
> +          />
There's no h1 so h2 doesn't have a parent aswell. This should probably a list. Don't want to make another round of review and since Marcin mentioned he wants this to go in I'll resolve

2022-04-28 07:53 UTC, sethidden approved these changes
Accepting based on Marcin's comment about the a11y fixes supposed to be done later

2022-04-28 08:08 UTC, merged