feat: write docs and export useApi and its type from ~/composables
vuestorefront/magento2 pull request #930
Opened 2022-04-26 21:36 UTC by VitorLuizC

## Description

- Allow developers to declare generic params for `query` and `mutate` methods;
- Define a type for `useApi` return;
- Named export `useApi` and `UseApiInterface` from '~/composables';
- Write TSDoc comments for useApi composable and its type.

## Related Issue

https://vsf.atlassian.net/browse/M2-373

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-04-27 07:37 UTC, sethidden requested changes
(blocking because I need to test some alternatives on the local branch)

2022-04-27 07:46 UTC, sethidden commented on packages/theme/composables/useApi/UseApi.ts
> +import type { Variables } from 'graphql-request';
I know all the other composables have their own dedicated Use[ComposableName].ts file with the types, but we've actually been speaking about removing those and just merging the `use[ComposableName].ts` code into the `index.ts` file so both the "JS" code and TS types are in a single index.ts file.

The reason for this is this interface isn't reused anywhere - it's not meant to be extended. So it's easier to just make changes in a single index.ts file, rather than in both (if you eg. add some new feature to a composable).

Would it be possible to remove this file and have it all in-one in index.ts? ie. would api-extractor work well with that?

2022-04-27 07:48 UTC, sethidden commented on packages/theme/composables/useApi/index.ts
> -type Request = <T = any, V = Variables>(document: string, variables?: V, requestHeaders?: HeadersInit) => Promise<T>;
In the PR you mention
```
Allow developers to declare generic params for query and mutate methods;
```
but this is already possible on `develop`.

Would it be possible to keep it as-is? Ie. `const query : Request = `? The arguments of query and mutate are identical so the type made sense to me when I was writing it

2022-04-27 07:50 UTC, sethidden commented on packages/theme/composables/useApi/index.ts
> +    headers?: HeadersInit,
The types are in UseApiInterface so it'd be nice if they didn't need to be duplicated in index.ts. Though with my earlier suggestion of removing UseApi.ts this comment could resolve itself

2022-04-27 07:55 UTC, sethidden commented on packages/theme/composables/useApi/index.ts
> + *         const result = await query(GET_CART_PRICE_QUERY, { cartId }, {
```suggestion
 *         const result = await query<SomeDummyType>(GET_CART_PRICE_QUERY, { cartId }, {
```
May be worth demonstrating that passing a generic is possible (don't treat the suggestion verbatim, I'm just not sure how to name SomeDummyType :P)

2022-04-27 07:57 UTC, sethidden commented on packages/theme/composables/useApi/index.ts
> + *         price.value = result.data?.cart?.prices?.[0]?.subtotal_excluding_tax?.value ?? null;
Hmm now that I see the `result.data?` I'm thinking the type of `query` should be something like `<T = any, V = Variables> (document, variables, somearg) => Promise<ApolloResponse<T>>`.

Otherwise users will always have to manually write `query<ApolloResponse<TheActualType>>`

2022-04-27 12:50 UTC, VitorLuizC commented on packages/theme/composables/useApi/index.ts
> -type Request = <T = any, V = Variables>(document: string, variables?: V, requestHeaders?: HeadersInit) => Promise<T>;
Yeap, I clearly misunderstood the generics. I'll rollback this type and use it in the `UseApiInterface`.

2022-04-27 13:09 UTC, VitorLuizC commented on packages/theme/composables/useApi/index.ts
> + *         price.value = result.data?.cart?.prices?.[0]?.subtotal_excluding_tax?.value ?? null;
My example is wrong. I read both [`graphql-request`](https://github.com/prisma-labs/graphql-request) docs and types, and it really resolves the `Promise` with data instead of the response object.

I'll fix my example.

2022-04-28 08:52 UTC, sethidden approved these changes

2022-04-28 13:20 UTC, merged