fix: prevent content jump when variant is selected on PDP
vuestorefront/magento2 pull request #933
Opened 2022-04-27 11:41 UTC by bartoszherba

## Description
prevent content jump when a variant is selected on PDP

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-04-27 12:06 UTC, sethidden requested changes
reviewing

2022-04-27 12:40 UTC, sethidden requested changes

2022-04-27 12:40 UTC, sethidden commented on packages/theme/composables/useCart/useCart.ts
> +  loading: Readonly<Ref<boolean>>;
With this change:
![image](https://user-images.githubusercontent.com/5359825/165515795-e2148181-f639-4a70-bf8c-73da6f8942f4.png)


Without this change (previous):
![image](https://user-images.githubusercontent.com/5359825/165515678-d2237ffa-808a-432d-9a6a-349ac544af5d.png)

Should stay as is imo
```suggestion
  loading: DeepReadonly<Ref<boolean>>;
```

2022-04-27 12:40 UTC, sethidden commented on packages/theme/composables/useReview/useReview.ts
> +  loading: Readonly<Ref<boolean>>;
Same as in previous comment

2022-04-27 12:40 UTC, sethidden commented on packages/theme/pages/Product.vue
> +      if (Boolean(product?.value?.sku) === false) nuxtError({ statusCode: 404 });
```suggestion
      if (!Boolean(product?.value?.sku)) nuxtError({ statusCode: 404 });
```
nitpick, can commit through github

2022-04-27 12:40 UTC, sethidden commented on packages/theme/pages/Product.vue
> +          ? [...productReviews].shift()
```suggestion
          ? productReviews[0]
```

I know this is just a diff because you moved the code from above but this is so weird that I felt the need to leave a comment.

shift() removes the first element from the array (mutates the array) and returns the first element. So here a new array is created just for the sake of getting the first element from it. This doesn't even create any new references or anything

2022-04-27 12:40 UTC, sethidden commented on packages/theme/pages/Product.vue
> +      if (firstFetch) {
I understand this is here to accomodate the client-side changes (eg. changing color of a clothing item)

If some logic is "firstFetch" it means that it's either client-side or server-side, but if some logic is NOT "firstFetch", it means it's only client-side (ie. you can't change color of clothes on PDP on the serverside - it's always done on the client side).

Imo if something is client-side, it shouldn't be in useFetch, since useFetch is used for bot client-side and server-side logic.

2022-04-27 12:40 UTC, sethidden commented on packages/theme/pages/Product.vue
> +    const updateProductConfiguration = (label, value) => {
```suggestion
    const updateProductConfiguration = (label: SomeType, value: SomeType) => {
```

2022-04-27 12:40 UTC, sethidden commented on packages/theme/pages/Product.vue
> +              <template v-if="product !== null && product.__typename === 'GroupedProduct'">
It's possible to avoid the condition duplication
```suggestion
          <template v-if="product !== null>
              <template v-if="product.__typename === 'GroupedProduct'">
              ...
              </template>
              <template v-else-if="product.__typename === 'someotherproductwhatever'">
              </template>
```

2022-04-27 12:43 UTC, sethidden commented on packages/theme/pages/Product.vue
> +              <template v-if="product !== null && product.__typename === 'GroupedProduct'">
The more nested templates can be removed aswell by just putting v-if directly on the grouped-product-selector

2022-04-27 12:55 UTC, bartoszherba commented on packages/theme/composables/useCart/useCart.ts
> +  loading: Readonly<Ref<boolean>>;
![Screenshot 2022-04-27 at 14 52 25](https://user-images.githubusercontent.com/16045377/165522239-5d895cfd-4182-461d-8ca9-84983f47c7db.png)

And Readonly perfectly align with the loading data structure.

/**
 * Make all properties in T readonly
 */
type Readonly<T> = {
    readonly [P in keyof T]: T[P];
};

2022-04-27 13:08 UTC, bartoszherba commented on packages/theme/pages/Product.vue
> +          ? [...productReviews].shift()
ok

2022-04-27 13:09 UTC, bartoszherba commented on packages/theme/pages/Product.vue
> +    const updateProductConfiguration = (label, value) => {
ok

2022-04-27 13:12 UTC, bartoszherba commented on packages/theme/pages/Product.vue
> +              <template v-if="product !== null && product.__typename === 'GroupedProduct'">
ok

2022-04-27 13:14 UTC, bartoszherba commented on packages/theme/pages/Product.vue
> +      if (firstFetch) {
Ultimately the whole page must be reworked to align with our modular approach and decomposition of components, but this is why we have tasks to do that so we can do smaller, intermediate steps.

2022-04-27 13:15 UTC, bartoszherba commented on packages/theme/composables/useCart/useCart.ts
> +  loading: Readonly<Ref<boolean>>;
IDK why do you have `const loading: any` in the first place

2022-04-28 05:48 UTC, bartoszherba commented on packages/theme/pages/Product.vue
> +      if (firstFetch) {
I made an improvement to avoid "if"

2022-04-28 08:07 UTC, sethidden approved these changes

2022-04-28 08:15 UTC, merged