test: categoryEmptyResults component
vuestorefront/magento2 pull request #934
Opened 2022-04-27 13:38 UTC by Diegoalbag

## Description

Added tests for CategoryEmpty results component
## Related Issue

https://vsf.atlassian.net/jira/software/c/projects/M2/boards/51/backlog?view=detail&selectedIssue=M2-440&issueLimit=100
## Motivation and Context

## How Has This Been Tested?

yarn test:theme
## Screenshots (if appropriate):
<img width="798" alt="Screen Shot 2022-04-27 at 9 37 16 AM" src="https://user-images.githubusercontent.com/72459310/165531383-437899c7-7b1d-4ebc-9de5-2c025eb229d3.png">

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-04-27 13:42 UTC, Frodigo requested changes

2022-04-27 13:42 UTC, Frodigo commented on packages/theme/modules/catalog/category/components/__tests__/CategoryEmptyResults.spec.ts
> +import { shallowMount, config } from '@vue/test-utils'
Could you use the render method from `@testing-library/vue` instead of vue test-utils? Take a look at this file for reference: `packages/theme/components/__tests__/AddtoWishlist.spec.js`

2022-04-28 05:34 UTC, bartoszherba requested changes

2022-04-28 05:34 UTC, bartoszherba commented on packages/theme/modules/catalog/category/components/__tests__/CategoryEmptyResults.spec.ts
> +  }
Could you add this to `packages/theme/jest-setup.js` instead? I think that such a mock can be used globally.

2022-04-28 05:34 UTC, bartoszherba commented on packages/theme/modules/catalog/category/components/__tests__/CategoryEmptyResults.spec.ts
> +    const p = queryByText(`We can't find products matching the selection.`);
Can you rename `svg` and `p` to something more meaningful, so the reader will know what's being tested?

2022-04-28 05:34 UTC, bartoszherba commented on packages/theme/modules/catalog/category/components/__tests__/CategoryEmptyResults.spec.ts
> +  it('Renders content from a slot override', () => {
```suggestion
  it('Renders content from the "default" slot', () => {
```

2022-04-29 10:20 UTC, Frodigo approved these changes

2022-04-29 10:21 UTC, merged