docs: update `useAddresses` API reference (M2-553)
vuestorefront/magento2 pull request #935
Opened 2022-04-27 15:19 UTC by filipsobol

This PR updates the documentation for the `useAddresses` composable.

2022-04-28 08:21 UTC, bartoszherba requested changes

2022-04-28 08:21 UTC, bartoszherba commented on packages/theme/composables/useAddresses/index.ts
> +  const save = async (params: ComposableFunctionArgs<UseAddressesParamsInput>) => {
```suggestion
  const save = async (params?: ComposableFunctionArgs<UseAddressesParamsInput>) => {
```
Otherwise I will be forced to pass something like a `{}`

2022-04-28 08:21 UTC, bartoszherba commented on packages/api-client/src/api/createCustomerAddress/index.ts
> +import type { CustomQuery } from '@vue-storefront/core';
```suggestion
import type { CustomQuery } from '~/types/core';
```

2022-04-28 08:21 UTC, bartoszherba commented on packages/theme/composables/useAddresses/index.ts
> +  const save = async (params: ComposableFunctionArgs<UseAddressesParamsInput>) => {
Places like `params.prop` should be also updated

2022-05-10 06:07 UTC, Frodigo submitted a review, later dismissed

2022-05-10 06:20 UTC, bartoszherba requested changes

2022-05-10 06:20 UTC, bartoszherba commented on packages/theme/composables/index.ts
> +export * from '../modules/customer/composables/useAddresses';
Please, revert that change, keep it as it was in the whole file.

2022-05-10 06:20 UTC, bartoszherba commented on packages/theme/modules/customer/composables/useAddresses/index.ts
> +import { transformUserCreateAddressInput, transformUserUpdateAddressInput } from '../../helpers/userAddressManipulator';
```suggestion
import { transformUserCreateAddressInput, transformUserUpdateAddressInput } from '~/modules/customer/helpers/userAddressManipulator';
```

2022-05-10 06:20 UTC, bartoszherba commented on packages/theme/modules/customer/composables/useAddresses/useAddresses.ts
> +  update(params?: ComposableFunctionArgs<UseAddressesParamsInput>): Promise<CustomerAddress>;
Params for update should be required, right?

2022-05-10 06:20 UTC, bartoszherba commented on packages/theme/modules/customer/composables/useAddresses/useAddresses.ts
> +  remove(params?: ComposableFunctionArgs<UseAddressesParamsInput>): Promise<boolean>;
```suggestion
  remove(params: ComposableFunctionArgs<UseAddressesParamsInput>): Promise<boolean>;
```

2022-05-10 06:20 UTC, bartoszherba commented on packages/theme/modules/customer/composables/useAddresses/useAddresses.ts
> +  update(params?: ComposableFunctionArgs<UseAddressesParamsInput>): Promise<CustomerAddress>;
```suggestion
  update(params: ComposableFunctionArgs<UseAddressesParamsInput>): Promise<CustomerAddress>;
```

2022-05-10 06:20 UTC, bartoszherba commented on packages/theme/types/plugins.d.ts
> +import type { GraphQLClient } from 'graphql-request';
I don't like this change, I prefer to keep such declarations close to the plugin so, if I want to remove/update the plugin I have to change one file instead of two; there is no benefit in moving that here, especially if task is about `useAddresses` @Frodigo @sethidden

2022-05-10 06:20 UTC, bartoszherba commented on scripts/templates/tsconfig.theme.json
> +  "extends": "./tsconfig.json",
Why do we update tsconfig? Is this PR about ts config at all? There is no ``./tsconfig.json`

2022-05-10 07:50 UTC, filipsobol commented on packages/theme/composables/index.ts
> +export * from '../modules/customer/composables/useAddresses';
`api-extractors` throws an error with the old approach. From the description it looks like a limitation of that library.

2022-05-10 07:54 UTC, filipsobol commented on scripts/templates/tsconfig.theme.json
> +  "extends": "./tsconfig.json",
This file is temporarily moved to the `theme` folder to generate the API reference and deleted afterward. It has a configuration specific to the needs of API reference generation.

2022-05-10 08:07 UTC, bartoszherba commented on packages/theme/composables/index.ts
> +export * from '../modules/customer/composables/useAddresses';
oks

2022-05-10 08:22 UTC, bartoszherba submitted a review, later dismissed

2022-05-10 10:33 UTC, bartoszherba approved these changes

2022-05-11 06:15 UTC, bartoszherba approved these changes

2022-05-11 08:39 UTC, merged