feat: add skeleton loaders in category navbar
vuestorefront/magento2 pull request #936
Opened 2022-04-28 08:14 UTC by bartoszherba

## Description
add skeleton loaders in category navbar

## How Has This Been Tested?

- Visit category page, execute any action eg. add filter
- Observe that skeletons are now masking loaded fields

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-04-29 09:57 UTC, sethidden requested changes
CategoryNavbar still has some layout shift on narrow viewports. I'm only talking about the layout shift in CategoryNavbar, not the other ones (sidebar etc), since this PR is only about Category Navbar
https://user-images.githubusercontent.com/5359825/165923395-18646955-6136-4e03-972a-05219edd4e72.mov

2022-04-29 09:57 UTC, sethidden commented on packages/theme/components/SkeletonLoader/index.vue
> +  <div
At this point you can remove componentClass and possibly componentStyle since if you do `<Skeleton loader :style="{ margin: 0 }"` or something the :style and :class will be passed to the root element

This'd be annyoing to replace all skeletons in the whole app but just be aware, no action needed - it's potentially just more flexible since you don't have to add a new prop for margin, width, height

2022-04-29 12:32 UTC, bartoszherba commented on packages/theme/components/SkeletonLoader/index.vue
> +  <div
I really do not want to rework skeleton loaders in this issue ;/
Though I fixed layout issues for a mobile view

2022-05-04 10:51 UTC, Frodigo approved these changes

2022-05-04 11:50 UTC, sethidden approved these changes

2022-05-04 11:50 UTC, merged