feat: replaced images from cdn.shopify by images from cloudinary
vuestorefront/magento2 pull request #941
Opened 2022-04-28 19:28 UTC by AlexanderDevitsky

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-04-29 06:54 UTC, bartoszherba requested changes
@AlexanderDevitsky 
I think that the main issue with this PR is that you implemented your own nuxt-img solution but we already have SfImage which covers all needs. You can find an example here `packages/theme/pages/Checkout/Payment.vue` 
```<SfImage
            image-tag="nuxt-img"
            :src="getMagentoImage(cartGetters.getItemImage(product))"
            :alt="cartGetters.getItemName(product)"
            :width="imageSizes.checkout.imageWidth"
            :height="imageSizes.checkout.imageHeight"
            :nuxt-img-config="{
              fit: 'cover',
            }"
          />```

2022-04-29 06:54 UTC, bartoszherba commented on packages/theme/components/CallToAction.vue
> +<script>
Please add `lang="ts`
Do not push changes with the `--no-verify` flag.

2022-04-29 06:54 UTC, bartoszherba commented on packages/theme/components/CallToAction.vue
> +      type: Object,
Please add object type `PropType<type>`

2022-04-29 06:54 UTC, bartoszherba commented on packages/theme/components/CallToAction.vue
> +      default: null,
```suggestion
      default: '',
```

2022-04-29 06:54 UTC, bartoszherba commented on packages/theme/components/Hero.vue
> +      default: null,
```suggestion
      default: '',
```
('' === null) === false && (typeof null === 'string') === false

2022-04-29 06:54 UTC, bartoszherba commented on packages/theme/components/Hero.vue
> +      type: Object,
Please add PropType

2022-04-29 06:54 UTC, bartoszherba commented on packages/theme/components/Hero.vue
> +    const image = props.image;
Can you use SfImage instead, so we avoid custom implementation? SfImage has everything you need and will align with all other parts of application. SfImage supports nuxt image.

2022-04-29 06:54 UTC, bartoszherba commented on packages/theme/pages/Home.vue
> +        desktop: '/w_1240,h_400,c_fit/homepage/bannerB.webp',
This is hard to use, please use SfImage as suggested above.

2022-04-29 06:54 UTC, bartoszherba commented on packages/theme/pages/Home.vue
> +      :image="{
Please use SfImage instead of a custom implementation.

2022-04-29 06:54 UTC, bartoszherba commented on packages/theme/pages/Home.vue
>      <LoadWhenVisible>
Please move CTA back inside the LWV component, or if it yields issues (why?) then remove empty LWV component.

2022-04-29 11:26 UTC, AlexanderDevitsky commented
@bartoszherba Thank you for the review! I have a few more questions. What if we need to load images of different sizes for desktop and mobile devices. In this case, we need to use two `<SfImage>` components that will have different `width` and `height` props for desktop and mobile? Also this implementation has been done to use `background-image`. Should I replace logic and use `SfImage` component with `object-fit: cover` property for the image in this case?

2022-04-29 11:59 UTC, bartoszherba commented
@AlexanderDevitsky This is a hard question, we are using CDN or Redis or both, in such case the pattern will be to determine if we are on mobile or desktop in `mounted` hook and with some ifology display only the mobile or desktop content. If we hide stuff with CSS we will over fetch images in two sizes. I am not sure if this is in the scope of this task anyway, we have a lot of such places that are not covered yet. On mounted hook will be able to return proper device because it will be executed once all cache/cdn html/scripts are already loaded.

And yes please, replace all images with SfImage, configure it as a nuxt image. Should you use cover? IDK, it depends. Eg. on PDP we do not crop images but I imagine that in a banner, the image must take defined space and some should be cropped. So It is up to the context. In most we use `cover` though but maybe `inside` will be more appropriate in a banner? IMO we can use fit, it is a configurable thing and the final implementation can be very easily adjusted.

2022-04-29 15:41 UTC, AlexanderDevitsky commented
@bartoszherba I have added some changes. Please check if this is enough

2022-05-11 06:35 UTC, bartoszherba approved these changes

2022-05-11 06:35 UTC, merged