test: CategoryNavbar.vue component
vuestorefront/magento2 pull request #952
Opened 2022-05-05 19:32 UTC by Diegoalbag

## Description

Added unit tests for packages/theme/modules/catalog/category/components/navbar/CategoryNavbar.vue
## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):
<img width="680" alt="Screen Shot 2022-05-05 at 3 25 27 PM" src="https://user-images.githubusercontent.com/72459310/167010647-c29e966a-e642-45fd-8616-4b7918971529.png">

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-05-09 07:09 UTC, bartoszherba requested changes
@Diegoalbag Please, fix also the PR name so it align with the rules (remove the dot ;) )

2022-05-09 07:09 UTC, bartoszherba commented on packages/theme/modules/catalog/category/components/navbar/__tests__/CategoryNavbar.spec.js
> +  it('Should render "sort by" select and change selection', async() => {
Can we also verify that select has all expected options based on its data?

2022-05-09 07:09 UTC, bartoszherba commented on packages/theme/modules/catalog/category/components/navbar/__tests__/CategoryNavbar.spec.js
> +});
I think that we can also add the following tests:
1. Check if the items count is rendered properly with the expected value
2. Check if the component is in loading state all skeletons are rendered as expected
3. change sorting action emits 'reloadProducts' event

2022-05-09 07:09 UTC, bartoszherba commented on packages/theme/modules/catalog/category/components/navbar/__tests__/CategoryNavbar.spec.js
> +import { expect } from '@jest/globals';
![Screenshot 2022-05-09 at 09 08 14](https://user-images.githubusercontent.com/16045377/167358044-ab8595a8-e136-4cea-92a6-706f8894eb5b.png)
It is not required to import assertion anyway.

2022-05-17 10:47 UTC, bartoszherba commented on packages/theme/modules/catalog/category/components/navbar/__tests__/CategoryNavbar.spec.js
> +import { expect } from '@jest/globals';
@Diegoalbag What about this one?

2022-05-17 10:47 UTC, bartoszherba commented on packages/theme/modules/catalog/category/components/navbar/__tests__/CategoryNavbar.spec.js
> +  it('Should render "sort by" select and change selection', async() => {
@Diegoalbag What about this one?

2022-05-17 10:47 UTC, bartoszherba commented on packages/theme/modules/catalog/category/components/navbar/__tests__/CategoryNavbar.spec.js
> +});
@Diegoalbag What about this one?

2022-05-17 11:59 UTC, sethidden commented
I recently added a GitHub action step that runs ESLint and fails if there are any ESLint errors.
If the build action starts failing in this PR, please:
1. Rebase the branch from this PR on develop then push out the changes.
2. If that doesn't work, this means your new code has some linting errors. Please go to the repository root (where the .git folder is) and run `yarn lint`

2022-05-17 12:09 UTC, Diegoalbag commented on packages/theme/modules/catalog/category/components/navbar/__tests__/CategoryNavbar.spec.js
> +import { expect } from '@jest/globals';
@bartoszherba Assertion is not being imported anymore.

2022-05-17 12:11 UTC, Diegoalbag commented on packages/theme/modules/catalog/category/components/navbar/__tests__/CategoryNavbar.spec.js
> +    expect(options.length).toBe(categoryNavbarProps.props.sortBy.options.length);
@bartoszherba here I verify that select has all expected options based on its data

2022-05-17 12:12 UTC, Diegoalbag commented on packages/theme/modules/catalog/category/components/navbar/__tests__/CategoryNavbar.spec.js
> +    expect(emitted().reloadProducts).toHaveProperty('length', 1);
@bartoszherba Here I check that changing sorting action emits 'reloadProducts' event

2022-05-17 15:34 UTC, Diegoalbag commented on packages/theme/modules/catalog/category/components/navbar/__tests__/CategoryNavbar.spec.js
> +  it('Should render Skeleton when loading is true', () => {
@bartoszherba  Check if the component is in loading state all skeletons are rendered as expected

2022-05-18 06:29 UTC, bartoszherba approved these changes

2022-05-18 06:29 UTC, merged