refactor: category page
vuestorefront/magento2 pull request #953
Opened 2022-05-06 12:11 UTC by bartoszherba

## Description
- move breadcrumbs logic to the breadcrumbs component
- rework useFacet composable

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-05-06 12:13 UTC, bartoszherba commented on packages/theme/modules/catalog/category/components/cms/categoryContent.gql.ts
> +    categoryList(filters: $filters) {
category is deprecated, i fixed that here.

2022-05-09 10:35 UTC, sethidden requested changes

2022-05-09 10:35 UTC, sethidden commented on packages/theme/modules/catalog/category/components/views/useProductsWithCommonCardProps.ts
> -    const link = context.app.localePath(`/p/${getProductSku(product)}${getSlug(product, product.categories[0])}`);
Do you mind using the less string-operation intensive object-based approach here?
```ts
context.app.localeRoute({ name: 'product', params: { id: getProductSku(product), slug: getSlug(product, product.categories[0])
```
You may need to slice the getSlug(product, product.categories[0]) to get the redundant '/' from the beginning

2022-05-09 10:35 UTC, sethidden commented on packages/theme/modules/catalog/category/composables/useFacet/SortingOptions.ts
> +}
optiona: Given the names of the keys largely correspond with the values you could use a string union instead of an enum

```ts
export type SortingOptionsValuesEnum = "" | "name_ASC" | "name_DESC" | "price_ASC" | "price_DESC"
```

(you lose the description of "" as "DEFAULT" though). I wrote this because there's a lot of critique of TS enums, ie. they get compiled down to objects so they contribute to the bundle size, where string unions are just JS strings.

2022-05-09 10:35 UTC, sethidden commented on packages/theme/modules/catalog/category/composables/useFacet/index.ts
> +  const result = ref<UseFacetSearchResult<any>>({ data: null, input: null });
Can a better type be used here? I get that you don't know what type will come back, but consider:

1. Adding a generic type argument to the useFacet composition function  
```ts
export function useFacet<TData, TInput>() {
   ref<UseFacetSearchResult<data: TData, input: TInput>
}
```
or just `<TResult extends { data: unknown | null, input: unknown | null }>` (note the unknown isntead of any meaning "I don't know what types are there - force me to do some type checks like `if(typeof x === string)` before attempting any operation instead of the any behavior of "just let me do anything")

2022-05-09 10:35 UTC, sethidden commented on packages/theme/modules/catalog/category/composables/useFacet/index.ts
> +        perPageOptions: PerPageOptions,
not sure if this single usage of PerPageOptions warrants a separate file. keeping it as a non-exported const seems fine

2022-05-09 10:35 UTC, sethidden commented on packages/theme/modules/catalog/category/getters/facetGetters.ts
> +    pageOptions: [10, 50, 100],
since there's a dedicated page options (if it's deemed still necessary) with the [10,20,30] array, this could be moved to that file?

2022-05-09 10:35 UTC, sethidden commented on packages/theme/modules/catalog/pages/category.vue
> -      }
I'm worried that traverseCategoryTree won't be be able to access the categories because they won't be loaded.

I know the sidebar also loads categories in the catalog, but the loading inside category.vue (page root) makes the most sense since it's the entrypoint.

It seems fragile to rely on the categories/filters to load the categories for category.vue.

This should be probably done in router middleware anyway but I'd keep this for now

2022-05-09 10:35 UTC, sethidden commented on packages/theme/modules/catalog/category/components/breadcrumbs/CategoryBreadcrumbs.vue
> +<style lang="scss">
```suggestion
<style lang="scss" scoped>
```

2022-05-09 10:37 UTC, sethidden commented on packages/theme/modules/catalog/category/composables/useFacet/index.ts
> +        perPageOptions: PerPageOptions,
In a later comment I found another instance of perPageOptions and suggested to maybe move it to that file, so there are 2 options: keep 2 instances in the file, or remove the file altoghether and inline the code

2022-05-09 12:37 UTC, bartoszherba commented on packages/theme/modules/catalog/category/composables/useFacet/SortingOptions.ts
> +}
I know about the issues with enums and I am aware of what you propose but that would be the third convention for enums in this project so let's keep it as it is and eventually rework all places in the future.

2022-05-09 12:44 UTC, bartoszherba commented on packages/theme/modules/catalog/category/composables/useFacet/index.ts
> +        perPageOptions: PerPageOptions,
From the customizability standpoint, it is better to have config things in a separate file. We need to think a little wider, like - can we expect to reuse this in the project? Definitely, we can and that's it. It can be even used somewhere else for calculations or other stuff. Keep responsibilities separated is a good approach.

2022-05-09 12:47 UTC, bartoszherba commented on packages/theme/modules/catalog/category/getters/facetGetters.ts
> +    pageOptions: [10, 50, 100],
I used PerPageOptoions for the consistency.

2022-05-09 12:49 UTC, bartoszherba commented on packages/theme/modules/catalog/pages/category.vue
> -      }
It does not have to be loaded, the active category is a computed prop based on the router path. An active category is the only thing I need on the category page at this point.

2022-05-09 12:50 UTC, bartoszherba commented on packages/theme/modules/catalog/category/components/breadcrumbs/CategoryBreadcrumbs.vue
> +<style lang="scss">
oks, fixed

2022-05-09 13:02 UTC, bartoszherba commented on packages/theme/modules/catalog/category/components/views/useProductsWithCommonCardProps.ts
> -    const link = context.app.localePath(`/p/${getProductSku(product)}${getSlug(product, product.categories[0])}`);
No, I don't mind, it's your code ;)))

2022-05-10 07:03 UTC, sethidden commented on packages/theme/modules/catalog/category/components/views/useProductsWithCommonCardProps.ts
> -    const link = context.app.localePath(`/p/${getProductSku(product)}${getSlug(product, product.categories[0])}`);
It's not mine :P I'm just the last in the blame

2022-05-10 07:14 UTC, sethidden approved these changes

2022-05-10 09:11 UTC, sethidden approved these changes

2022-05-10 09:12 UTC, merged