fix: invalid prices on grouped and configurable product
vuestorefront/magento2 pull request #971
Opened 2022-05-09 12:34 UTC by bartoszherba

- fix issue with initial grouped product price resolving

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-05-09 12:35 UTC, sethidden approved these changes

2022-05-10 09:47 UTC, sethidden requested changes
temporary block - reviewing

2022-05-10 09:55 UTC, sethidden submitted a review, later dismissed
Left some optional comments

2022-05-10 10:01 UTC, bartoszherba commented on packages/theme/modules/catalog/pricing/__tests__/getConfigurableProductPriceCommand.spec.ts
> +    // @ts-ignore for the simplified mock structure
Ok, fixed.

2022-05-10 10:15 UTC, sethidden commented on packages/theme/modules/catalog/pricing/getGroupedProductPriceCommand.ts
> +  };
suits me ¯\_(ツ)_/¯

2022-05-10 10:16 UTC, sethidden commented on packages/theme/modules/catalog/product/enums/ProductTypeEnum.ts
> +export type ProductTypeEnum = 'SimpleProduct' | 'ConfigurableProduct' | 'BundleProduct' | 'GroupedProduct';
this is just about the name, using unions or enums is fine

2022-05-10 13:30 UTC, merged